// Editorial starter collection, not a claim about measured worldwide frequency.
// Use catalog spellings (including emoji presentation selectors where present).
export const popularSymbolGroups = {
  typography: [
    '—',
    '–',
    '…',
    '«',
    '»',
    '“',
    '”',
    '„',
    '‘',
    '’',
    '‹',
    '›',
    '•',
    '·',
    '№',
    '©',
    '®',
    '™',
    '§',
    '¶',
    '†',
    '‡',
    '′',
    '″',
    '\u00a0',
    '\u202f',
    '\u2009',
    '¿',
    '¡',
    '״',
    '׳',
  ],
  currency: ['$', '€', '£', '¥', '₽', '₴', '₪', '₹', '₩', '₺', '¢', '₿'],
  math: [
    '±',
    '−',
    '×',
    '÷',
    '=',
    '≠',
    '≈',
    '≤',
    '≥',
    '∞',
    '√',
    '∑',
    '°',
    '%',
    '‰',
    '¹',
    '²',
    '³',
    '½',
    '¼',
    '¾',
  ],
  arrows: ['←', '→', '↑', '↓', '↔', '↕', '⇒', '⇐', '⇔', '↗', '↘'],
  marks: ['✓', '✔', '✕', '★', '☆', '♪', '\u0301', '\u0308'],
  emoji: [
    '😀',
    '😃',
    '😄',
    '😁',
    '😅',
    '😂',
    '🤣',
    '😊',
    '🙂',
    '😉',
    '😍',
    '🥰',
    '😘',
    '😎',
    '🤔',
    '🤨',
    '🙃',
    '😐',
    '😔',
    '😢',
    '😭',
    '😡',
    '🤯',
    '😱',
    '😴',
    '🤦',
    '🤷',
    '👍',
    '👎',
    '👌',
    '👏',
    '🙌',
    '🙏',
    '💪',
    '👋',
    '🤝',
    '❤',
    '💔',
    '💕',
    '💯',
    '🔥',
    '✨',
    '🎉',
    '🎊',
    '🎂',
    '🎁',
    '🚀',
    '💡',
    '✅',
    '❌',
    '⚠',
    '❓',
    '❗',
    '👀',
    '💬',
    '📌',
    '🔗',
    '🔒',
    '☕',
    '🍀',
  ],
} as const;

export const popularSymbols: readonly string[] =
  Object.values(popularSymbolGroups).flat();
const positions = new Map(
  popularSymbols.map((symbol, index) => [symbol, index]),
);
export const popularSymbolPosition = (symbol: string) =>
  positions.get(symbol) ?? Infinity;
export const isPopularSymbol = (symbol: string) => positions.has(symbol);

export const popularSymbolLabels = {
  en: 'Popular',
  ru: 'Популярные',
  pl: 'Popularne',
  fr: 'Populaires',
  de: 'Beliebt',
  es: 'Populares',
  pt: 'Populares',
  it: 'Popolari',
  ro: 'Populare',
  he: 'נפוצים',
  ar: 'الشائعة',
  tr: 'Popüler',
  vi: 'Phổ biến',
  nl: 'Populair',
};

export const allSymbolLabels = {
  en: 'All symbols',
  ru: 'Все символы',
  pl: 'Wszystkie symbole',
  fr: 'Tous les symboles',
  de: 'Alle Zeichen',
  es: 'Todos los símbolos',
  pt: 'Todos os símbolos',
  it: 'Tutti i simboli',
  ro: 'Toate simbolurile',
  he: 'כל הסימנים',
  ar: 'كل الرموز',
  tr: 'Tüm simgeler',
  vi: 'Tất cả ký hiệu',
  nl: 'Alle symbolen',
};
