import type { Locale } from './typing-engine';

export const symbolNames: Record<string, Record<Locale, string>> = {
  '`': {
    tr: 'ters tırnak',
    nl: 'backtick',
    vi: 'dấu nháy ngược',
    ar: 'علامة اقتباس معكوسة',
    en: 'backtick',
    he: 'גרש הפוך',
    ru: 'обратная кавычка',
    pl: 'odwrócony apostrof',
    fr: 'accent grave',
    de: 'Gravis',
    es: 'acento grave',
    pt: 'acento grave',
    it: 'accento grave',
    ro: 'accent grav',
  },
  '¹': {
    tr: 'üst simge bir',
    nl: 'superscript één',
    vi: 'số một trên cao',
    ar: 'واحد علوي',
    en: 'superscript one',
    he: 'אחת בכתב עילי',
    ru: 'единица в верхнем индексе',
    pl: 'jedynka w indeksie górnym',
    fr: 'un en exposant',
    de: 'hochgestellte Eins',
    es: 'uno en superíndice',
    pt: 'um sobrescrito',
    it: 'uno in apice',
    ro: 'unu la exponent',
  },
  '²': {
    tr: 'üst simge iki',
    nl: 'superscript twee',
    vi: 'số hai trên cao',
    ar: 'اثنان علوي',
    en: 'superscript two',
    he: 'שתיים בכתב עילי',
    ru: 'двойка в верхнем индексе',
    pl: 'dwójka w indeksie górnym',
    fr: 'deux en exposant',
    de: 'hochgestellte Zwei',
    es: 'dos en superíndice',
    pt: 'dois sobrescrito',
    it: 'due in apice',
    ro: 'doi la exponent',
  },
  '³': {
    tr: 'üst simge üç',
    nl: 'superscript drie',
    vi: 'số ba trên cao',
    ar: 'ثلاثة علوي',
    en: 'superscript three',
    he: 'שלוש בכתב עילי',
    ru: 'тройка в верхнем индексе',
    pl: 'trójka w indeksie górnym',
    fr: 'trois en exposant',
    de: 'hochgestellte Drei',
    es: 'tres en superíndice',
    pt: 'três sobrescrito',
    it: 'tre in apice',
    ro: 'trei la exponent',
  },
  '¡': {
    tr: 'ters ünlem',
    nl: 'omgekeerd uitroepteken',
    vi: 'dấu chấm than ngược',
    ar: 'علامة تعجب مقلوبة',
    en: 'inverted exclamation mark',
    he: 'סימן קריאה הפוך',
    ru: 'перевёрнутый восклицательный знак',
    pl: 'odwrócony wykrzyknik',
    fr: 'point d’exclamation inversé',
    de: 'umgekehrtes Ausrufezeichen',
    es: 'signo de apertura de exclamación',
    pt: 'ponto de exclamação invertido',
    it: 'punto esclamativo capovolto',
    ro: 'semn de exclamare inversat',
  },
  '¹⁄₂': {
    tr: 'yarım',
    nl: 'een half',
    vi: 'một phần hai',
    ar: 'نصف',
    en: 'one half',
    he: 'חצי',
    ru: 'одна вторая',
    pl: 'jedna druga',
    fr: 'un demi',
    de: 'ein Halb',
    es: 'un medio',
    pt: 'um meio',
    it: 'un mezzo',
    ro: 'o doime',
  },
  '¹⁄₃': {
    tr: 'üçte bir',
    nl: 'een derde',
    vi: 'một phần ba',
    ar: 'ثلث',
    en: 'one third',
    he: 'שליש',
    ru: 'одна треть',
    pl: 'jedna trzecia',
    fr: 'un tiers',
    de: 'ein Drittel',
    es: 'un tercio',
    pt: 'um terço',
    it: 'un terzo',
    ro: 'o treime',
  },
  '¹⁄₄': {
    tr: 'dörtte bir',
    nl: 'een kwart',
    vi: 'một phần tư',
    ar: 'ربع',
    en: 'one quarter',
    he: 'רבע',
    ru: 'одна четверть',
    pl: 'jedna czwarta',
    fr: 'un quart',
    de: 'ein Viertel',
    es: 'un cuarto',
    pt: 'um quarto',
    it: 'un quarto',
    ro: 'un sfert',
  },
  $: {
    tr: 'dolar',
    nl: 'dollar',
    vi: 'đô la',
    ar: 'دولار',
    en: 'dollar',
    he: 'דולר',
    ru: 'доллар',
    pl: 'dolar',
    fr: 'dollar',
    de: 'Dollar',
    es: 'dólar',
    pt: 'dólar',
    it: 'dollaro',
    ro: 'dolar',
  },
  '‰': {
    tr: 'binde',
    nl: 'promille',
    vi: 'phần nghìn',
    ar: 'بالألف',
    en: 'per mille',
    he: 'פרומיל',
    ru: 'промилле',
    pl: 'promil',
    fr: 'pour mille',
    de: 'Promille',
    es: 'por mil',
    pt: 'por mil',
    it: 'per mille',
    ro: 'la mie',
  },
  '↑': {
    tr: 'yukarı ok',
    nl: 'pijl omhoog',
    vi: 'mũi tên lên',
    ar: 'سهم للأعلى',
    en: 'up arrow',
    he: 'חץ למעלה',
    ru: 'стрелка вверх',
    pl: 'strzałka w górę',
    fr: 'flèche vers le haut',
    de: 'Pfeil nach oben',
    es: 'flecha hacia arriba',
    pt: 'seta para cima',
    it: 'freccia in su',
    ro: 'săgeată în sus',
  },
  '¿': {
    tr: 'ters soru işareti',
    nl: 'omgekeerd vraagteken',
    vi: 'dấu hỏi ngược',
    ar: 'علامة استفهام مقلوبة',
    en: 'inverted question mark',
    he: 'סימן שאלה הפוך',
    ru: 'перевёрнутый вопросительный знак',
    pl: 'odwrócony pytajnik',
    fr: 'point d’interrogation inversé',
    de: 'umgekehrtes Fragezeichen',
    es: 'signo de apertura de interrogación',
    pt: 'ponto de interrogação invertido',
    it: 'punto interrogativo capovolto',
    ro: 'semn de întrebare inversat',
  },
  '∞': {
    tr: 'sonsuzluk',
    nl: 'oneindigheid',
    vi: 'vô cực',
    ar: 'اللانهاية',
    en: 'infinity',
    he: 'אינסוף',
    ru: 'бесконечность',
    pl: 'nieskończoność',
    fr: 'infini',
    de: 'Unendlichkeit',
    es: 'infinito',
    pt: 'infinito',
    it: 'infinito',
    ro: 'infinit',
  },
  '←': {
    tr: 'sol ok',
    nl: 'pijl links',
    vi: 'mũi tên trái',
    ar: 'سهم لليسار',
    en: 'left arrow',
    he: 'חץ שמאלה',
    ru: 'стрелка влево',
    pl: 'strzałka w lewo',
    fr: 'flèche vers la gauche',
    de: 'Pfeil nach links',
    es: 'flecha hacia la izquierda',
    pt: 'seta para a esquerda',
    it: 'freccia a sinistra',
    ro: 'săgeată la stânga',
  },
  '→': {
    tr: 'sağ ok',
    nl: 'pijl rechts',
    vi: 'mũi tên phải',
    ar: 'سهم لليمين',
    en: 'right arrow',
    he: 'חץ ימינה',
    ru: 'стрелка вправо',
    pl: 'strzałka w prawo',
    fr: 'flèche vers la droite',
    de: 'Pfeil nach rechts',
    es: 'flecha hacia la derecha',
    pt: 'seta para a direita',
    it: 'freccia a destra',
    ro: 'săgeată la dreapta',
  },
  '‹': {
    tr: 'sol tek açılı tırnak',
    nl: 'enkel aanhalingsteken links',
    vi: 'ngoặc kép góc đơn trái',
    ar: 'علامة اقتباس زاوية مفردة يسرى',
    en: 'left single guillemet',
    he: 'מירכאה זוויתית יחידה שמאלית',
    ru: 'левая одинарная ёлочка',
    pl: 'lewy pojedynczy cudzysłów ostrokątny',
    fr: 'guillemet simple gauche',
    de: 'linkes einfaches Guillemets',
    es: 'comilla angular simple izquierda',
    pt: 'aspa angular simples esquerda',
    it: 'virgoletta angolare singola sinistra',
    ro: 'ghilimea unghiulară simplă stângă',
  },
  '›': {
    tr: 'sağ tek açılı tırnak',
    nl: 'enkel aanhalingsteken rechts',
    vi: 'ngoặc kép góc đơn phải',
    ar: 'علامة اقتباس زاوية مفردة يمنى',
    en: 'right single guillemet',
    he: 'מירכאה זוויתית יחידה ימנית',
    ru: 'правая одинарная ёлочка',
    pl: 'prawy pojedynczy cudzysłów ostrokątny',
    fr: 'guillemet simple droit',
    de: 'rechtes einfaches Guillemets',
    es: 'comilla angular simple derecha',
    pt: 'aspa angular simples direita',
    it: 'virgoletta angolare singola destra',
    ro: 'ghilimea unghiulară simplă dreaptă',
  },
  '—': {
    tr: 'uzun çizgi',
    nl: 'gedachtestreepje',
    vi: 'gạch ngang dài',
    ar: 'شرطة طويلة',
    en: 'em dash',
    he: 'קו מפריד ארוך',
    ru: 'длинное тире',
    pl: 'pauza',
    fr: 'tiret cadratin',
    de: 'Geviertstrich',
    es: 'raya',
    pt: 'travessão',
    it: 'lineetta lunga',
    ro: 'linie de pauză lungă',
  },
  '–': {
    tr: 'orta çizgi',
    nl: 'half kastlijntje',
    vi: 'gạch ngang vừa',
    ar: 'شرطة متوسطة',
    en: 'en dash',
    he: 'קו מפריד קצר',
    ru: 'короткое тире',
    pl: 'półpauza',
    fr: 'tiret demi-cadratin',
    de: 'Halbgeviertstrich',
    es: 'semirraya',
    pt: 'meia-risca',
    it: 'lineetta media',
    ro: 'linie de pauză scurtă',
  },
  '≠': {
    tr: 'eşit değil',
    nl: 'niet gelijk aan',
    vi: 'không bằng',
    ar: 'لا يساوي',
    en: 'not equal',
    he: 'לא שווה',
    ru: 'не равно',
    pl: 'nierówność',
    fr: 'différent de',
    de: 'ungleich',
    es: 'distinto de',
    pt: 'diferente de',
    it: 'diverso da',
    ro: 'diferit de',
  },
  '±': {
    tr: 'artı eksi',
    nl: 'plusminus',
    vi: 'cộng trừ',
    ar: 'زائد أو ناقص',
    en: 'plus–minus',
    he: 'פלוס־מינוס',
    ru: 'плюс-минус',
    pl: 'plus minus',
    fr: 'plus ou moins',
    de: 'Plusminus',
    es: 'más menos',
    pt: 'mais ou menos',
    it: 'più o meno',
    ro: 'plus sau minus',
  },
  '✓': {
    tr: 'onay işareti',
    nl: 'vinkje',
    vi: 'dấu kiểm',
    ar: 'علامة صح',
    en: 'check mark',
    he: 'סימן אישור',
    ru: 'галочка',
    pl: 'znak wyboru',
    fr: 'coche',
    de: 'Häkchen',
    es: 'marca de verificación',
    pt: 'marca de verificação',
    it: 'segno di spunta',
    ro: 'bifă',
  },
  '⌃': {
    tr: 'Control tuşu simgesi',
    nl: 'Control-toetssymbool',
    vi: 'ký hiệu phím Control',
    ar: 'رمز مفتاح Control',
    en: 'Control key symbol',
    he: 'סמל מקש Control',
    ru: 'знак клавиши Control',
    pl: 'symbol klawisza Control',
    fr: 'symbole de la touche Contrôle',
    de: 'Symbol der Control-Taste',
    es: 'símbolo de la tecla Control',
    pt: 'símbolo da tecla Control',
    it: 'simbolo del tasto Control',
    ro: 'simbolul tastei Control',
  },
  '€': {
    tr: 'avro',
    nl: 'euro',
    vi: 'euro',
    ar: 'يورو',
    en: 'euro',
    he: 'אירו',
    ru: 'евро',
    pl: 'euro',
    fr: 'euro',
    de: 'Euro',
    es: 'euro',
    pt: 'euro',
    it: 'euro',
    ro: 'euro',
  },
  '⌥': {
    tr: 'Option tuşu simgesi',
    nl: 'Option-toetssymbool',
    vi: 'ký hiệu phím Option',
    ar: 'رمز مفتاح Option',
    en: 'Option key symbol',
    he: 'סמל מקש Option',
    ru: 'знак клавиши Option',
    pl: 'symbol klawisza Option',
    fr: 'symbole de la touche Option',
    de: 'Symbol der Option-Taste',
    es: 'símbolo de la tecla Option',
    pt: 'símbolo da tecla Option',
    it: 'simbolo del tasto Option',
    ro: 'simbolul tastei Option',
  },
  '®': {
    tr: 'tescilli marka',
    nl: 'geregistreerd handelsmerk',
    vi: 'nhãn hiệu đã đăng ký',
    ar: 'علامة تجارية مسجلة',
    en: 'registered trademark',
    he: 'סימן מסחר רשום',
    ru: 'зарегистрированный товарный знак',
    pl: 'zarejestrowany znak towarowy',
    fr: 'marque déposée',
    de: 'eingetragene Marke',
    es: 'marca registrada',
    pt: 'marca registada',
    it: 'marchio registrato',
    ro: 'marcă înregistrată',
  },
  '™': {
    tr: 'ticari marka',
    nl: 'handelsmerk',
    vi: 'nhãn hiệu',
    ar: 'علامة تجارية',
    en: 'trademark',
    he: 'סימן מסחר',
    ru: 'товарный знак',
    pl: 'znak towarowy',
    fr: 'marque commerciale',
    de: 'Markenzeichen',
    es: 'marca comercial',
    pt: 'marca comercial',
    it: 'marchio commerciale',
    ro: 'marcă comercială',
  },
  '#': {
    tr: 'numara işareti',
    nl: 'hekje',
    vi: 'dấu thăng',
    ar: 'علامة الرقم',
    en: 'number sign',
    he: 'סולמית',
    ru: 'решётка',
    pl: 'kratka',
    fr: 'croisillon',
    de: 'Raute',
    es: 'almohadilla',
    pt: 'cardinal',
    it: 'cancelletto',
    ro: 'diez',
  },
  ѣ: {
    tr: 'küçük yat',
    nl: 'kleine jat',
    vi: 'chữ yat thường',
    ar: 'يات صغير',
    en: 'lowercase yat',
    he: 'יאט קטנה',
    ru: 'строчная ять',
    pl: 'mała litera jat´',
    fr: 'yat minuscule',
    de: 'kleines Jat',
    es: 'yat minúscula',
    pt: 'yat minúsculo',
    it: 'jat minuscola',
    ro: 'iat mic',
  },
  Ѣ: {
    tr: 'büyük yat',
    nl: 'hoofdletter jat',
    vi: 'chữ yat hoa',
    ar: 'يات كبير',
    en: 'uppercase yat',
    he: 'יאט גדולה',
    ru: 'прописная ять',
    pl: 'wielka litera jat´',
    fr: 'yat majuscule',
    de: 'großes Jat',
    es: 'yat mayúscula',
    pt: 'yat maiúsculo',
    it: 'jat maiuscola',
    ro: 'iat mare',
  },
  ѵ: {
    tr: 'küçük ijitsa',
    nl: 'kleine izjitsa',
    vi: 'chữ izhitsa thường',
    ar: 'إيجيتسا صغير',
    en: 'lowercase izhitsa',
    he: 'איז׳יצה קטנה',
    ru: 'строчная ижица',
    pl: 'mała litera iżica',
    fr: 'ijitsa minuscule',
    de: 'kleines Ischiza',
    es: 'izhitsa minúscula',
    pt: 'izhitsa minúsculo',
    it: 'ižica minuscola',
    ro: 'ijiță mică',
  },
  Ѵ: {
    tr: 'büyük ijitsa',
    nl: 'hoofdletter izjitsa',
    vi: 'chữ izhitsa hoa',
    ar: 'إيجيتسا كبير',
    en: 'uppercase izhitsa',
    he: 'איז׳יצה גדולה',
    ru: 'прописная ижица',
    pl: 'wielka litera iżica',
    fr: 'ijitsa majuscule',
    de: 'großes Ischiza',
    es: 'izhitsa mayúscula',
    pt: 'izhitsa maiúsculo',
    it: 'ižica maiuscola',
    ro: 'ijiță mare',
  },
  і: {
    tr: 'küçük Kiril i',
    nl: 'kleine Cyrillische i',
    vi: 'chữ i Kirin thường',
    ar: 'حرف i سيريلي صغير',
    en: 'lowercase Cyrillic i',
    he: 'אי קירילית קטנה',
    ru: 'строчная и десятеричная',
    pl: 'mała litera i cyrylickie',
    fr: 'i cyrillique minuscule',
    de: 'kleines kyrillisches I',
    es: 'i cirílica minúscula',
    pt: 'i cirílico minúsculo',
    it: 'i cirillica minuscola',
    ro: 'i chirilic mic',
  },
  І: {
    tr: 'büyük Kiril i',
    nl: 'hoofdletter Cyrillische i',
    vi: 'chữ i Kirin hoa',
    ar: 'حرف i سيريلي كبير',
    en: 'uppercase Cyrillic i',
    he: 'אי קירילית גדולה',
    ru: 'прописная и десятеричная',
    pl: 'wielka litera i cyrylickie',
    fr: 'i cyrillique majuscule',
    de: 'großes kyrillisches I',
    es: 'i cirílica mayúscula',
    pt: 'i cirílico maiúsculo',
    it: 'i cirillica maiuscola',
    ro: 'i chirilic mare',
  },
  ѳ: {
    tr: 'küçük fita',
    nl: 'kleine fita',
    vi: 'chữ fita thường',
    ar: 'فيتا صغير',
    en: 'lowercase fita',
    he: 'פיטה קטנה',
    ru: 'строчная фита',
    pl: 'mała litera fita',
    fr: 'fita minuscule',
    de: 'kleines Fita',
    es: 'fita minúscula',
    pt: 'fita minúsculo',
    it: 'fita minuscola',
    ro: 'fita mică',
  },
  Ѳ: {
    tr: 'büyük fita',
    nl: 'hoofdletter fita',
    vi: 'chữ fita hoa',
    ar: 'فيتا كبير',
    en: 'uppercase fita',
    he: 'פיטה גדולה',
    ru: 'прописная фита',
    pl: 'wielka litera fita',
    fr: 'fita majuscule',
    de: 'großes Fita',
    es: 'fita mayúscula',
    pt: 'fita maiúsculo',
    it: 'fita maiuscola',
    ro: 'fita mare',
  },
  '′': {
    tr: 'asal işareti',
    nl: 'priem',
    vi: 'dấu phẩy trên',
    ar: 'علامة أولية',
    en: 'prime',
    he: 'פריים',
    ru: 'штрих',
    pl: 'prim',
    fr: 'prime',
    de: 'Minutenzeichen',
    es: 'prima',
    pt: 'primo',
    it: 'primo',
    ro: 'prim',
  },
  '″': {
    tr: 'çift asal işareti',
    nl: 'dubbele priem',
    vi: 'dấu phẩy trên kép',
    ar: 'علامة أولية مزدوجة',
    en: 'double prime',
    he: 'פריים כפול',
    ru: 'двойной штрих',
    pl: 'bis',
    fr: 'double prime',
    de: 'Sekundenzeichen',
    es: 'doble prima',
    pt: 'duplo primo',
    it: 'secondo',
    ro: 'secund',
  },
  '[': {
    tr: 'sol köşeli parantez',
    nl: 'vierkante haak openen',
    vi: 'ngoặc vuông trái',
    ar: 'قوس مربع أيسر',
    en: 'left square bracket',
    he: 'סוגר מרובע שמאלי',
    ru: 'левая квадратная скобка',
    pl: 'lewy nawias kwadratowy',
    fr: 'crochet ouvrant',
    de: 'öffnende eckige Klammer',
    es: 'corchete de apertura',
    pt: 'parêntese reto de abertura',
    it: 'parentesi quadra aperta',
    ro: 'paranteză pătrată deschisă',
  },
  ']': {
    tr: 'sağ köşeli parantez',
    nl: 'vierkante haak sluiten',
    vi: 'ngoặc vuông phải',
    ar: 'قوس مربع أيمن',
    en: 'right square bracket',
    he: 'סוגר מרובע ימני',
    ru: 'правая квадратная скобка',
    pl: 'prawy nawias kwadratowy',
    fr: 'crochet fermant',
    de: 'schließende eckige Klammer',
    es: 'corchete de cierre',
    pt: 'parêntese reto de fecho',
    it: 'parentesi quadra chiusa',
    ro: 'paranteză pătrată închisă',
  },
  '{': {
    tr: 'sol süslü parantez',
    nl: 'accolade openen',
    vi: 'ngoặc nhọn trái',
    ar: 'قوس معقوف أيسر',
    en: 'left curly bracket',
    he: 'סוגר מסולסל שמאלי',
    ru: 'левая фигурная скобка',
    pl: 'lewy nawias klamrowy',
    fr: 'accolade ouvrante',
    de: 'öffnende geschweifte Klammer',
    es: 'llave de apertura',
    pt: 'chaveta de abertura',
    it: 'parentesi graffa aperta',
    ro: 'acoladă deschisă',
  },
  '}': {
    tr: 'sağ süslü parantez',
    nl: 'accolade sluiten',
    vi: 'ngoặc nhọn phải',
    ar: 'قوس معقوف أيمن',
    en: 'right curly bracket',
    he: 'סוגר מסולסל ימני',
    ru: 'правая фигурная скобка',
    pl: 'prawy nawias klamrowy',
    fr: 'accolade fermante',
    de: 'schließende geschweifte Klammer',
    es: 'llave de cierre',
    pt: 'chaveta de fecho',
    it: 'parentesi graffa chiusa',
    ro: 'acoladă închisă',
  },
  '≈': {
    tr: 'yaklaşık eşit',
    nl: 'ongeveer gelijk aan',
    vi: 'xấp xỉ bằng',
    ar: 'يساوي تقريبًا',
    en: 'approximately equal',
    he: 'שווה בקירוב',
    ru: 'приблизительно равно',
    pl: 'w przybliżeniu równe',
    fr: 'environ égal',
    de: 'ungefähr gleich',
    es: 'aproximadamente igual',
    pt: 'aproximadamente igual',
    it: 'circa uguale',
    ro: 'aproximativ egal',
  },
  '⌘': {
    tr: 'Command tuşu simgesi',
    nl: 'Command-toetssymbool',
    vi: 'ký hiệu phím Command',
    ar: 'رمز مفتاح Command',
    en: 'Command key symbol',
    he: 'סמל מקש Command',
    ru: 'знак клавиши Command',
    pl: 'symbol klawisza Command',
    fr: 'symbole de la touche Commande',
    de: 'Symbol der Command-Taste',
    es: 'símbolo de la tecla Command',
    pt: 'símbolo da tecla Command',
    it: 'simbolo del tasto Command',
    ro: 'simbolul tastei Command',
  },
  '§': {
    tr: 'bölüm işareti',
    nl: 'paragraafteken',
    vi: 'dấu mục',
    ar: 'علامة القسم',
    en: 'section sign',
    he: 'סימן סעיף',
    ru: 'параграф',
    pl: 'paragraf',
    fr: 'paragraphe',
    de: 'Paragraphenzeichen',
    es: 'signo de sección',
    pt: 'parágrafo',
    it: 'paragrafo',
    ro: 'paragraf',
  },
  '⇧': {
    tr: 'Shift tuşu simgesi',
    nl: 'Shift-toetssymbool',
    vi: 'ký hiệu phím Shift',
    ar: 'رمز مفتاح Shift',
    en: 'Shift key symbol',
    he: 'סמל מקש Shift',
    ru: 'знак клавиши Shift',
    pl: 'symbol klawisza Shift',
    fr: 'symbole de la touche Maj',
    de: 'Symbol der Umschalttaste',
    es: 'símbolo de la tecla Mayús',
    pt: 'símbolo da tecla Shift',
    it: 'simbolo del tasto Maiusc',
    ro: 'simbolul tastei Shift',
  },
  '°': {
    tr: 'derece',
    nl: 'graad',
    vi: 'độ',
    ar: 'درجة',
    en: 'degree',
    he: 'מעלה',
    ru: 'градус',
    pl: 'stopień',
    fr: 'degré',
    de: 'Grad',
    es: 'grado',
    pt: 'grau',
    it: 'grado',
    ro: 'grad',
  },
  '⌀': {
    tr: 'çap',
    nl: 'diameter',
    vi: 'đường kính',
    ar: 'قطر',
    en: 'diameter',
    he: 'קוטר',
    ru: 'диаметр',
    pl: 'średnica',
    fr: 'diamètre',
    de: 'Durchmesser',
    es: 'diámetro',
    pt: 'diâmetro',
    it: 'diametro',
    ro: 'diametru',
  },
  '£': {
    tr: 'sterlin',
    nl: 'Brits pond',
    vi: 'bảng Anh',
    ar: 'جنيه إسترليني',
    en: 'pound sterling',
    he: 'לירה שטרלינג',
    ru: 'фунт стерлингов',
    pl: 'funt szterling',
    fr: 'livre sterling',
    de: 'Pfund Sterling',
    es: 'libra esterlina',
    pt: 'libra esterlina',
    it: 'sterlina',
    ro: 'liră sterlină',
  },
  '': {
    tr: 'Apple logosu',
    nl: 'Apple-logo',
    vi: 'biểu trưng Apple',
    ar: 'شعار Apple',
    en: 'Apple logo',
    he: 'סמל Apple',
    ru: 'логотип Apple',
    pl: 'logo Apple',
    fr: 'logo Apple',
    de: 'Apple-Logo',
    es: 'logotipo de Apple',
    pt: 'logótipo da Apple',
    it: 'logo Apple',
    ro: 'sigla Apple',
  },
  '₽': {
    tr: 'ruble',
    nl: 'roebel',
    vi: 'rúp',
    ar: 'روبل',
    en: 'ruble',
    he: 'רובל',
    ru: 'рубль',
    pl: 'rubel',
    fr: 'rouble',
    de: 'Rubel',
    es: 'rublo',
    pt: 'rublo',
    it: 'rublo',
    ro: 'rublă',
  },
  '„': {
    tr: 'alt çift tırnak',
    nl: 'laag dubbel aanhalingsteken',
    vi: 'ngoặc kép dưới',
    ar: 'علامة اقتباس مزدوجة سفلية',
    en: 'double low quotation mark',
    he: 'מירכאות כפולות תחתונות',
    ru: 'двойная нижняя кавычка',
    pl: 'dolny cudzysłów podwójny',
    fr: 'guillemet double bas',
    de: 'unteres doppeltes Anführungszeichen',
    es: 'comilla doble baja',
    pt: 'aspa dupla inferior',
    it: 'virgolette doppie basse',
    ro: 'ghilimea dublă jos',
  },
  '“': {
    tr: 'sol çift tırnak',
    nl: 'dubbel aanhalingsteken links',
    vi: 'ngoặc kép trái',
    ar: 'علامة اقتباس مزدوجة يسرى',
    en: 'left double quotation mark',
    he: 'מירכאות כפולות שמאליות',
    ru: 'левая двойная кавычка',
    pl: 'lewy cudzysłów podwójny',
    fr: 'guillemet double gauche',
    de: 'linkes doppeltes Anführungszeichen',
    es: 'comilla doble izquierda',
    pt: 'aspa dupla esquerda',
    it: 'virgolette doppie sinistre',
    ro: 'ghilimea dublă stângă',
  },
  '”': {
    tr: 'sağ çift tırnak',
    nl: 'dubbel aanhalingsteken rechts',
    vi: 'ngoặc kép phải',
    ar: 'علامة اقتباس مزدوجة يمنى',
    en: 'right double quotation mark',
    he: 'מירכאות כפולות ימניות',
    ru: 'правая двойная кавычка',
    pl: 'prawy cudzysłów podwójny',
    fr: 'guillemet double droit',
    de: 'rechtes doppeltes Anführungszeichen',
    es: 'comilla doble derecha',
    pt: 'aspa dupla direita',
    it: 'virgolette doppie destre',
    ro: 'ghilimea dublă dreaptă',
  },
  '‘': {
    tr: 'sol tek tırnak',
    nl: 'enkel gekruld aanhalingsteken links',
    vi: 'nháy đơn trái',
    ar: 'علامة اقتباس مفردة يسرى',
    en: 'left single quotation mark',
    he: 'מירכאה יחידה שמאלית',
    ru: 'левая одинарная кавычка',
    pl: 'lewy cudzysłów pojedynczy',
    fr: 'guillemet simple gauche',
    de: 'linkes einfaches Anführungszeichen',
    es: 'comilla simple izquierda',
    pt: 'aspa simples esquerda',
    it: 'virgoletta singola sinistra',
    ro: 'ghilimea simplă stângă',
  },
  '’': {
    tr: 'sağ tek tırnak',
    nl: 'enkel gekruld aanhalingsteken rechts',
    vi: 'nháy đơn phải',
    ar: 'علامة اقتباس مفردة يمنى',
    en: 'right single quotation mark',
    he: 'מירכאה יחידה ימנית',
    ru: 'правая одинарная кавычка',
    pl: 'prawy cudzysłów pojedynczy',
    fr: 'guillemet simple droit',
    de: 'rechtes einfaches Anführungszeichen',
    es: 'comilla simple derecha',
    pt: 'aspa simples direita',
    it: 'virgoletta singola destra',
    ro: 'ghilimea simplă dreaptă',
  },
  '×': {
    tr: 'çarpma işareti',
    nl: 'vermenigvuldigingsteken',
    vi: 'dấu nhân',
    ar: 'علامة الضرب',
    en: 'multiplication sign',
    he: 'סימן כפל',
    ru: 'умножение',
    pl: 'znak mnożenia',
    fr: 'signe de multiplication',
    de: 'Malzeichen',
    es: 'signo de multiplicación',
    pt: 'sinal de multiplicação',
    it: 'segno di moltiplicazione',
    ro: 'semn de înmulțire',
  },
  '·': {
    tr: 'orta nokta',
    nl: 'middelpunt',
    vi: 'dấu chấm giữa',
    ar: 'نقطة وسطية',
    en: 'middle dot',
    he: 'נקודה אמצעית',
    ru: 'средняя точка',
    pl: 'kropka środkowa',
    fr: 'point médian',
    de: 'Mittelpunkt',
    es: 'punto medio',
    pt: 'ponto médio',
    it: 'punto mediano',
    ro: 'punct median',
  },
  '©': {
    tr: 'telif hakkı',
    nl: 'auteursrecht',
    vi: 'bản quyền',
    ar: 'حقوق النشر',
    en: 'copyright',
    he: 'זכויות יוצרים',
    ru: 'авторское право',
    pl: 'prawo autorskie',
    fr: 'droit d’auteur',
    de: 'Copyright',
    es: 'derechos de autor',
    pt: 'direitos de autor',
    it: 'diritto d’autore',
    ro: 'drepturi de autor',
  },
  '¢': {
    tr: 'sent',
    nl: 'cent',
    vi: 'xu',
    ar: 'سنت',
    en: 'cent',
    he: 'סנט',
    ru: 'цент',
    pl: 'cent',
    fr: 'cent',
    de: 'Cent',
    es: 'centavo',
    pt: 'cêntimo',
    it: 'centesimo',
    ro: 'cent',
  },
  '↓': {
    tr: 'aşağı ok',
    nl: 'pijl omlaag',
    vi: 'mũi tên xuống',
    ar: 'سهم للأسفل',
    en: 'down arrow',
    he: 'חץ למטה',
    ru: 'стрелка вниз',
    pl: 'strzałka w dół',
    fr: 'flèche vers le bas',
    de: 'Pfeil nach unten',
    es: 'flecha hacia abajo',
    pt: 'seta para baixo',
    it: 'freccia in giù',
    ro: 'săgeată în jos',
  },
  ß: {
    tr: 'küçük keskin s',
    nl: 'kleine ringel-s',
    vi: 'chữ s sắc thường',
    ar: 'حرف s حاد صغير',
    en: 'lowercase sharp s',
    he: 'אסצט קטנה',
    ru: 'строчный эсцет',
    pl: 'mała litera eszett',
    fr: 'eszett minuscule',
    de: 'kleines Eszett',
    es: 'eszett minúscula',
    pt: 'eszett minúsculo',
    it: 'eszett minuscola',
    ro: 'eszett mic',
  },
  ẞ: {
    tr: 'büyük keskin s',
    nl: 'hoofdletter ringel-s',
    vi: 'chữ s sắc hoa',
    ar: 'حرف s حاد كبير',
    en: 'uppercase sharp s',
    he: 'אסצט גדולה',
    ru: 'прописной эсцет',
    pl: 'wielka litera eszett',
    fr: 'eszett majuscule',
    de: 'großes Eszett',
    es: 'eszett mayúscula',
    pt: 'eszett maiúsculo',
    it: 'eszett maiuscola',
    ro: 'eszett mare',
  },
  '−': {
    tr: 'eksi işareti',
    nl: 'minteken',
    vi: 'dấu trừ',
    ar: 'علامة الطرح',
    en: 'minus sign',
    he: 'סימן מינוס',
    ru: 'минус',
    pl: 'minus',
    fr: 'signe moins',
    de: 'Minuszeichen',
    es: 'signo menos',
    pt: 'sinal de menos',
    it: 'segno meno',
    ro: 'semn minus',
  },
  '•': {
    tr: 'madde imi',
    nl: 'opsommingsteken',
    vi: 'dấu đầu dòng',
    ar: 'علامة تعداد',
    en: 'bullet',
    he: 'תבליט',
    ru: 'маркер списка',
    pl: 'punktor',
    fr: 'puce',
    de: 'Aufzählungspunkt',
    es: 'viñeta',
    pt: 'marcador',
    it: 'punto elenco',
    ro: 'marcator de listă',
  },
  '«': {
    tr: 'sol açılı tırnak',
    nl: 'dubbel punthaakje links',
    vi: 'ngoặc kép góc trái',
    ar: 'علامة اقتباس زاوية يسرى',
    en: 'left guillemet',
    he: 'מירכאות זוויתיות שמאליות',
    ru: 'левая ёлочка',
    pl: 'lewy cudzysłów ostrokątny',
    fr: 'guillemet ouvrant',
    de: 'linkes Guillemets',
    es: 'comilla angular izquierda',
    pt: 'aspa angular esquerda',
    it: 'virgolette caporali sinistre',
    ro: 'ghilimea unghiulară stângă',
  },
  '»': {
    tr: 'sağ açılı tırnak',
    nl: 'dubbel punthaakje rechts',
    vi: 'ngoặc kép góc phải',
    ar: 'علامة اقتباس زاوية يمنى',
    en: 'right guillemet',
    he: 'מירכאות זוויתיות ימניות',
    ru: 'правая ёлочка',
    pl: 'prawy cudzysłów ostrokątny',
    fr: 'guillemet fermant',
    de: 'rechtes Guillemets',
    es: 'comilla angular derecha',
    pt: 'aspa angular direita',
    it: 'virgolette caporali destre',
    ro: 'ghilimea unghiulară dreaptă',
  },
  '…': {
    tr: 'üç nokta',
    nl: 'beletselteken',
    vi: 'dấu ba chấm',
    ar: 'علامة الحذف',
    en: 'ellipsis',
    he: 'שלוש נקודות',
    ru: 'многоточие',
    pl: 'wielokropek',
    fr: 'points de suspension',
    de: 'Auslassungspunkte',
    es: 'puntos suspensivos',
    pt: 'reticências',
    it: 'puntini di sospensione',
    ro: 'puncte de suspensie',
  },
};
