import type { Locale } from './typing-engine.ts';

// Shared multilingual associations and explanations for every searchable family.
export const searchGroups: {
  symbols: string[];
  terms: Record<Locale, string>;
  description: Record<Locale, string>;
}[] = [
  {
    symbols: ['$', '€', '£', '₽', '¢'],
    terms: {
      tr: 'dolar|avro|sterlin|ruble|sent|para|birimi|para|fiyat',
      nl: 'dollar|euro|Brits pond|roebel|cent|valuta|geld|prijs',
      vi: 'đô la|euro|bảng Anh|rúp|xu|tiền|tệ|giá',
      ar: 'دولار|يورو|جنيه إسترليني|روبل|سنت|عملة|مال|سعر',

      en: 'currency|money|cash|price|payment',
      ru: 'валюта|деньги|оплата|цена|наличные',
      pl: 'waluta|pieniądze|gotówka|cena',
      fr: 'monnaie|argent|espèces|prix',
      de: 'Währung|Geld|Bargeld|Preis',
      es: 'moneda|dinero|efectivo|precio',
      pt: 'moeda|dinheiro|numerário|preço',
      it: 'valuta|soldi|contanti|prezzo',
      ro: 'valută|bani|numerar|preț',
      he: 'מטבע|כסף|מזומן|מחיר',
    },
    description: {
      tr: 'Para tutarları ve fiyatlarda kullanılan para birimi işareti.',
      nl: 'Valutateken voor geldbedragen en prijzen.',
      vi: 'Ký hiệu tiền tệ dùng với số tiền và giá cả.',
      ar: 'رمز عملة يُستخدم مع المبالغ والأسعار.',

      en: 'A currency sign used with monetary amounts and prices.',
      ru: 'Денежный знак: используется для записи сумм и цен.',
      pl: 'Symbol waluty używany przy kwotach i cenach.',
      fr: 'Symbole monétaire utilisé avec les montants et les prix.',
      de: 'Währungszeichen zur Angabe von Geldbeträgen und Preisen.',
      es: 'Símbolo monetario usado con cantidades y precios.',
      pt: 'Símbolo monetário usado em valores e preços.',
      it: 'Simbolo monetario usato con importi e prezzi.',
      ro: 'Simbol monetar folosit pentru sume și prețuri.',
      he: 'סימן מטבע המשמש לציון סכומים ומחירים.',
    },
  },
  {
    symbols: ['«', '»', '‹', '›', '„', '“', '”', '‘', '’', '`'],
    terms: {
      tr: 'sol açılı tırnak|sağ açılı tırnak|sol tek açılı tırnak|sağ tek açılı tırnak|alt çift tırnak|sol çift tırnak|sağ çift tırnak|sol tek tırnak|sağ tek tırnak|ters tırnak|tırnak|alıntı|konuşma',
      nl: 'dubbel punthaakje links|dubbel punthaakje rechts|enkel aanhalingsteken links|enkel aanhalingsteken rechts|laag dubbel aanhalingsteken|dubbel aanhalingsteken links|dubbel aanhalingsteken rechts|enkel gekruld aanhalingsteken links|enkel gekruld aanhalingsteken rechts|backtick|aanhalingsteken|citaat',
      vi: 'ngoặc kép góc trái|ngoặc kép góc phải|ngoặc kép góc đơn trái|ngoặc kép góc đơn phải|ngoặc kép dưới|ngoặc kép trái|ngoặc kép phải|nháy đơn trái|nháy đơn phải|dấu nháy ngược|ngoặc|kép|trích|dẫn',
      ar: 'علامة اقتباس زاوية يسرى|علامة اقتباس زاوية يمنى|علامة اقتباس زاوية مفردة يسرى|علامة اقتباس زاوية مفردة يمنى|علامة اقتباس مزدوجة سفلية|علامة اقتباس مزدوجة يسرى|علامة اقتباس مزدوجة يمنى|علامة اقتباس مفردة يسرى|علامة اقتباس مفردة يمنى|علامة اقتباس معكوسة|اقتباس|كلام',

      en: 'quotes|quotation|speech',
      ru: 'кавычки|цитата|речь',
      pl: 'cudzysłów|cytat|mowa',
      fr: 'citation|guillemets|paroles',
      de: 'Anführungszeichen|Zitat|Rede',
      es: 'comillas|cita|diálogo',
      pt: 'aspas|citação|diálogo',
      it: 'virgolette|citazione|dialogo',
      ro: 'ghilimele|citat|dialog',
      he: 'מירכאות|ציטוט|דיבור',
    },
    description: {
      tr: 'Tırnaklar alıntıyı veya doğrudan konuşmayı belirtir; kullanım dile göre değişir.',
      nl: 'Aanhalingstekens begrenzen citaten of directe rede; het gebruik verschilt per taal.',
      vi: 'Ngoặc kép bao quanh trích dẫn hoặc lời nói trực tiếp; quy tắc tùy ngôn ngữ.',
      ar: 'تحدّد علامات الاقتباس النص المنقول أو الكلام المباشر؛ وتختلف قواعدها حسب اللغة.',

      en: 'Quotation marks delimit quoted text or direct speech; conventions differ by language. A backtick also has uses in code.',
      ru: 'Кавычки выделяют цитаты и прямую речь. Их форма и расположение зависят от языка. Обратная кавычка также используется в коде.',
      pl: 'Cudzysłowy wydzielają cytaty i mowę; ich użycie zależy od języka. Odwrócony apostrof jest też używany w kodzie.',
      fr: 'Les guillemets délimitent les citations ; les conventions varient selon la langue. L’accent grave sert aussi dans le code.',
      de: 'Anführungszeichen begrenzen Zitate; ihre Verwendung hängt von der Sprache ab. Der Backtick wird auch in Code verwendet.',
      es: 'Las comillas delimitan citas; su uso depende del idioma. El acento grave también se usa en código.',
      pt: 'As aspas delimitam citações; as regras variam por idioma. O acento grave também é usado em código.',
      it: 'Le virgolette delimitano citazioni; le convenzioni variano per lingua. L’accento grave si usa anche nel codice.',
      ro: 'Ghilimelele delimitează citate; regulile depind de limbă. Accentul grav se folosește și în cod.',
      he: 'מירכאות תוחמות ציטוטים ודיבור ישיר; הכללים משתנים בין שפות. גרש הפוך משמש גם בקוד.',
    },
  },
  {
    symbols: ['←', '→', '↑', '↓'],
    terms: {
      tr: 'sol ok|sağ ok|yukarı ok|aşağı ok|ok|yön|hareket',
      nl: 'pijl links|pijl rechts|pijl omhoog|pijl omlaag|pijl|richting',
      vi: 'mũi tên trái|mũi tên phải|mũi tên lên|mũi tên xuống|mũi|tên|hướng',
      ar: 'سهم لليسار|سهم لليمين|سهم للأعلى|سهم للأسفل|سهم|اتجاه',

      en: 'arrow|direction|navigation|move',
      ru: 'стрелка|направление|движение|переход',
      pl: 'strzałka|kierunek|nawigacja',
      fr: 'flèche|direction|navigation',
      de: 'Pfeil|Richtung|Navigation',
      es: 'flecha|dirección|navegación',
      pt: 'seta|direção|navegação',
      it: 'freccia|direzione|navigazione',
      ro: 'săgeată|direcție|navigare',
      he: 'חץ|כיוון|ניווט',
    },
    description: {
      tr: 'Yön, hareket veya adımlar arasında geçiş gösterir.',
      nl: 'Geeft richting, beweging of een overgang tussen stappen aan.',
      vi: 'Biểu thị hướng, chuyển động hoặc chuyển bước.',
      ar: 'يشير إلى الاتجاه أو الحركة أو الانتقال بين الخطوات.',

      en: 'An arrow indicates direction, movement or a transition between steps.',
      ru: 'Стрелка обозначает направление, движение или переход между шагами.',
      pl: 'Strzałka wskazuje kierunek, ruch lub przejście między krokami.',
      fr: 'Une flèche indique une direction, un mouvement ou une transition.',
      de: 'Ein Pfeil zeigt eine Richtung, Bewegung oder einen Übergang an.',
      es: 'Una flecha indica dirección, movimiento o transición entre pasos.',
      pt: 'Uma seta indica direção, movimento ou transição entre etapas.',
      it: 'Una freccia indica direzione, movimento o passaggio tra fasi.',
      ro: 'O săgeată indică direcția, mișcarea sau trecerea între pași.',
      he: 'חץ מציין כיוון, תנועה או מעבר בין שלבים.',
    },
  },
  {
    symbols: ['≈', '≠', '±', '−', '×', '·', '∞'],
    terms: {
      tr: 'yaklaşık eşit|eşit değil|artı eksi|eksi işareti|çarpma işareti|orta nokta|sonsuzluk|matematik|işlem|formül',
      nl: 'ongeveer gelijk aan|niet gelijk aan|plusminus|minteken|vermenigvuldigingsteken|middelpunt|oneindigheid|wiskunde|bewerking|formule',
      vi: 'xấp xỉ bằng|không bằng|cộng trừ|dấu trừ|dấu nhân|dấu chấm giữa|vô cực|toán|phép|tính|công|thức',
      ar: 'يساوي تقريبًا|لا يساوي|زائد أو ناقص|علامة الطرح|علامة الضرب|نقطة وسطية|اللانهاية|رياضيات|عملية|صيغة',

      en: 'math|equation|calculation|operator',
      ru: 'математика|формула|вычисление|оператор',
      pl: 'matematyka|równanie|obliczenia',
      fr: 'mathématiques|équation|calcul',
      de: 'Mathematik|Gleichung|Rechnen',
      es: 'matemáticas|ecuación|cálculo',
      pt: 'matemática|equação|cálculo',
      it: 'matematica|equazione|calcolo',
      ro: 'matematică|ecuație|calcul',
      he: 'מתמטיקה|משוואה|חישוב',
    },
    description: {
      tr: 'Formüllerde işlem, ilişki veya değer gösteren matematik simgesi.',
      nl: 'Wiskundig symbool voor een bewerking, relatie of waarde in formules.',
      vi: 'Ký hiệu toán học biểu thị phép tính, quan hệ hoặc giá trị trong công thức.',
      ar: 'رمز رياضي يعبّر عن عملية أو علاقة أو قيمة في الصيغ.',

      en: 'A mathematical symbol used in formulas to express an operation, relation or value.',
      ru: 'Математический знак для записи операций, отношений или величин в формулах.',
      pl: 'Symbol matematyczny oznaczający działanie, relację lub wartość we wzorach.',
      fr: 'Symbole mathématique exprimant une opération, une relation ou une valeur.',
      de: 'Mathematisches Zeichen für Operationen, Beziehungen oder Werte in Formeln.',
      es: 'Símbolo matemático para operaciones, relaciones o valores en fórmulas.',
      pt: 'Símbolo matemático para operações, relações ou valores em fórmulas.',
      it: 'Simbolo matematico per operazioni, relazioni o valori nelle formule.',
      ro: 'Simbol matematic pentru operații, relații sau valori în formule.',
      he: 'סימן מתמטי לציון פעולה, יחס או ערך בנוסחאות.',
    },
  },
  {
    symbols: ['¹', '²', '³'],
    terms: {
      tr: 'üst simge bir|üst simge iki|üst simge üç',
      nl: 'superscript één|superscript twee|superscript drie',
      vi: 'số một trên cao|số hai trên cao|số ba trên cao',
      ar: 'واحد علوي|اثنان علوي|ثلاثة علوي',

      en: 'superscript|power|exponent|footnote',
      ru: 'степень|верхний индекс|сноска',
      pl: 'potęga|indeks górny|przypis',
      fr: 'exposant|puissance|note',
      de: 'Hochzahl|Potenz|Fußnote',
      es: 'superíndice|potencia|nota',
      pt: 'sobrescrito|potência|nota',
      it: 'apice|potenza|nota',
      ro: 'exponent|putere|notă',
      he: 'כתב עילי|חזקה|הערה',
    },
    description: {
      tr: 'Üsler, birimler veya dipnotlar için yukarıda yazılan rakam.',
      nl: 'Verhoogd cijfer voor machten, eenheden of voetnoten.',
      vi: 'Chữ số trên cao dùng cho lũy thừa, đơn vị hoặc chú thích.',
      ar: 'رقم علوي للأسس والوحدات والحواشي.',

      en: 'A raised digit used for powers, units and footnote references.',
      ru: 'Цифра в верхнем индексе: используется для степеней, единиц измерения и сносок.',
      pl: 'Cyfra w indeksie górnym służy do zapisu potęg, jednostek i przypisów.',
      fr: 'Chiffre en exposant utilisé pour les puissances, les unités et les notes.',
      de: 'Hochgestellte Ziffer für Potenzen, Einheiten und Fußnoten.',
      es: 'Dígito elevado usado para potencias, unidades y notas.',
      pt: 'Dígito elevado usado em potências, unidades e notas.',
      it: 'Cifra in apice usata per potenze, unità e note.',
      ro: 'Cifră ridicată folosită pentru puteri, unități și note.',
      he: 'ספרה עילית המשמשת לחזקות, יחידות והפניות להערות.',
    },
  },
  {
    symbols: ['¹⁄₂', '¹⁄₃', '¹⁄₄'],
    terms: {
      tr: 'yarım|üçte bir|dörtte bir',
      nl: 'een half|een derde|een kwart',
      vi: 'một phần hai|một phần ba|một phần tư',
      ar: 'نصف|ثلث|ربع',

      en: 'fraction|part|divide|recipe',
      ru: 'дробь|часть|деление|рецепт',
      pl: 'ułamek|część|dzielenie',
      fr: 'fraction|partie|division',
      de: 'Bruch|Teil|Division',
      es: 'fracción|parte|división',
      pt: 'fração|parte|divisão',
      it: 'frazione|parte|divisione',
      ro: 'fracție|parte|împărțire',
      he: 'שבר|חלק|חלוקה',
    },
    description: {
      tr: 'Üst pay, kesir çizgisi ve alt paydadan oluşan kesir.',
      nl: 'Breuk met verhoogde teller, breukstreep en verlaagde noemer.',
      vi: 'Phân số gồm tử số trên cao, gạch phân số và mẫu số dưới thấp.',
      ar: 'كسر من بسط علوي وشرطة كسر ومقام سفلي.',

      en: 'A fraction written as a sequence of a raised numerator, fraction slash and lowered denominator.',
      ru: 'Дробь из нескольких символов: числитель вверху, дробная черта и знаменатель внизу.',
      pl: 'Ułamek zapisany jako ciąg: licznik u góry, kreska ułamkowa i mianownik u dołu.',
      fr: 'Fraction composée d’un numérateur en exposant, d’une barre et d’un dénominateur en indice.',
      de: 'Bruch aus hochgestelltem Zähler, Bruchstrich und tiefgestelltem Nenner.',
      es: 'Fracción formada por numerador elevado, barra y denominador inferior.',
      pt: 'Fração formada por numerador elevado, barra e denominador inferior.',
      it: 'Frazione composta da numeratore in apice, barra e denominatore in pedice.',
      ro: 'Fracție formată din numărător ridicat, bară și numitor coborât.',
      he: 'שבר המורכב ממונה עילי, קו שבר ומכנה תחתי.',
    },
  },
  {
    symbols: ['—', '–'],
    terms: {
      tr: 'uzun çizgi|orta çizgi',
      nl: 'gedachtestreepje|half kastlijntje',
      vi: 'gạch ngang dài|gạch ngang vừa',
      ar: 'شرطة طويلة|شرطة متوسطة',

      en: 'dash|punctuation|pause|range|hyphen',
      ru: 'тире|дефис|пауза|диапазон|минус',
      pl: 'myślnik|pauza|zakres',
      fr: ' tiret|pause|intervalle',
      de: 'Gedankenstrich|Pause|Bereich',
      es: 'guion|raya|pausa|intervalo',
      pt: 'travessão|traço|pausa|intervalo',
      it: 'trattino|lineetta|pausa|intervallo',
      ro: 'liniuță|pauză|interval',
      he: 'קו מפריד|טווח|הפסקה',
    },
    description: {
      tr: 'Uzun çizgi cümle bölümlerini ayırır; orta çizgi 1–5 gibi aralıkları gösterir.',
      nl: 'Een gedachtestreepje scheidt zinsdelen; een half kastlijntje geeft bereiken aan, zoals 1–5.',
      vi: 'Gạch ngang dài tách các phần câu; gạch ngang vừa biểu thị khoảng như 1–5.',
      ar: 'تفصل الشرطة الطويلة أجزاء الجملة؛ والمتوسطة تدل على نطاق مثل 1–5.',

      en: 'The em dash separates parts of a sentence; the en dash commonly marks ranges such as 1–5.',
      ru: 'Длинное тире разделяет части предложения. Короткое тире часто обозначает диапазон, например 1–5.',
      pl: 'Pauza oddziela części zdania; półpauza często oznacza zakres, np. 1–5.',
      fr: 'Le tiret cadratin sépare des parties de phrase ; le demi-cadratin marque souvent un intervalle, comme 1–5.',
      de: 'Der Geviertstrich trennt Satzteile; der Halbgeviertstrich bezeichnet oft Bereiche wie 1–5.',
      es: 'La raya separa partes de una oración; el guion medio suele indicar intervalos, como 1–5.',
      pt: 'O travessão separa partes de uma frase; a meia-risca indica intervalos, como 1–5.',
      it: 'La lineetta lunga separa parti della frase; quella media indica intervalli, come 1–5.',
      ro: 'Linia lungă separă părți ale frazei; cea medie indică adesea intervale, precum 1–5.',
      he: 'קו מפריד ארוך מפריד חלקי משפט; קו בינוני מציין לעיתים טווחים כגון 1–5.',
    },
  },
  {
    symbols: ['⌘', '⌥', '⌃', '⇧'],
    terms: {
      tr: 'Command tuşu simgesi|Option tuşu simgesi|Control tuşu simgesi|Shift tuşu simgesi',
      nl: 'Command-toetssymbool|Option-toetssymbool|Control-toetssymbool|Shift-toetssymbool',
      vi: 'ký hiệu phím Command|ký hiệu phím Option|ký hiệu phím Control|ký hiệu phím Shift',
      ar: 'رمز مفتاح Command|رمز مفتاح Option|رمز مفتاح Control|رمز مفتاح Shift',

      en: 'keyboard|modifier|shortcut|hotkey',
      ru: 'клавиатура|модификатор|сочетание|горячая клавиша',
      pl: 'klawiatura|modyfikator|skrót',
      fr: 'clavier|modificateur|raccourci',
      de: 'Tastatur|Modifikator|Tastenkürzel',
      es: 'teclado|modificador|atajo',
      pt: 'teclado|modificador|atalho',
      it: 'tastiera|modificatore|scorciatoia',
      ro: 'tastatură|modificator|scurtătură',
      he: 'מקלדת|מקש שינוי|קיצור',
    },
    description: {
      tr: 'Özellikle Mac klavyelerinde birleşimler için kullanılan değiştirici simgesi.',
      nl: 'Symbool van een modificatietoets, vooral voor toetscombinaties op Mac.',
      vi: 'Ký hiệu phím bổ trợ dùng trong tổ hợp, đặc biệt trên Mac.',
      ar: 'رمز مفتاح تعديل لكتابة مجموعات المفاتيح، خصوصًا على Mac.',

      en: 'A keyboard modifier symbol used when writing key combinations, especially on Mac keyboards.',
      ru: 'Обозначение клавиши-модификатора в записи сочетаний клавиш, особенно на клавиатурах Mac.',
      pl: 'Symbol klawisza modyfikującego używany w skrótach, zwłaszcza na Macu.',
      fr: 'Symbole de touche modificatrice utilisé dans les raccourcis, notamment sur Mac.',
      de: 'Symbol einer Modifikatortaste in Tastenkombinationen, besonders am Mac.',
      es: 'Símbolo de tecla modificadora usado en atajos, especialmente en Mac.',
      pt: 'Símbolo de tecla modificadora usado em atalhos, sobretudo no Mac.',
      it: 'Simbolo di un tasto modificatore nelle scorciatoie, soprattutto su Mac.',
      ro: 'Simbol al unei taste modificatoare în scurtături, mai ales pe Mac.',
      he: 'סמל של מקש שינוי המשמש בכתיבת קיצורי מקלדת, במיוחד ב־Mac.',
    },
  },
  {
    symbols: ['ѣ', 'Ѣ', 'ѵ', 'Ѵ', 'і', 'І', 'ѳ', 'Ѳ'],
    terms: {
      tr: 'küçük yat|büyük yat|küçük ijitsa|büyük ijitsa|küçük Kiril i|büyük Kiril i|küçük fita|büyük fita',
      nl: 'kleine jat|hoofdletter jat|kleine izjitsa|hoofdletter izjitsa|kleine Cyrillische i|hoofdletter Cyrillische i|kleine fita|hoofdletter fita',
      vi: 'chữ yat thường|chữ yat hoa|chữ izhitsa thường|chữ izhitsa hoa|chữ i Kirin thường|chữ i Kirin hoa|chữ fita thường|chữ fita hoa',
      ar: 'يات صغير|يات كبير|إيجيتسا صغير|إيجيتسا كبير|حرف i سيريلي صغير|حرف i سيريلي كبير|فيتا صغير|فيتا كبير',

      en: 'letter|cyrillic|historical|old spelling',
      ru: 'буква|кириллица|дореформенная|старославянский',
      pl: 'litera|cyrylica|historyczna',
      fr: 'lettre|cyrillique|historique',
      de: 'Buchstabe|Kyrillisch|historisch',
      es: 'letra|cirílico|histórico',
      pt: 'letra|cirílico|histórico',
      it: 'lettera|cirillico|storico',
      ro: 'literă|chirilic|istoric',
      he: 'אות|קירילית|היסטורי',
    },
    description: {
      tr: 'Tarihî metinlerde görülen Kiril harfi; bazıları modern alfabelerde de kullanılır.',
      nl: 'Cyrillische letter uit historische teksten; sommige worden nog gebruikt in moderne alfabetten.',
      vi: 'Chữ Kirin trong văn bản lịch sử; một số vẫn dùng trong bảng chữ cái hiện đại.',
      ar: 'حرف سيريلي في النصوص التاريخية؛ لا يزال بعض هذه الحروف مستخدمًا في أبجديات حديثة.',

      en: 'A Cyrillic letter found in historical texts; some historical letters remain in modern alphabets.',
      ru: 'Кириллическая буква, встречающаяся в исторических текстах; часть таких букв сохранилась в современных алфавитах.',
      pl: 'Litera cyrylicka spotykana w dawnych tekstach; niektóre zachowały się we współczesnych alfabetach.',
      fr: 'Lettre cyrillique présente dans les textes anciens ; certaines subsistent dans les alphabets modernes.',
      de: 'Kyrillischer Buchstabe aus historischen Texten; einige werden noch in heutigen Alphabeten verwendet.',
      es: 'Letra cirílica presente en textos históricos; algunas siguen en alfabetos modernos.',
      pt: 'Letra cirílica presente em textos históricos; algumas permanecem em alfabetos modernos.',
      it: 'Lettera cirillica presente nei testi storici; alcune restano negli alfabeti moderni.',
      ro: 'Literă chirilică întâlnită în texte istorice; unele se păstrează în alfabete moderne.',
      he: 'אות קירילית המופיעה בטקסטים היסטוריים; חלקן משמשות גם באלפביתים מודרניים.',
    },
  },
  {
    symbols: ['ß', 'ẞ'],
    terms: {
      tr: 'küçük keskin s|büyük keskin s',
      nl: 'kleine ringel-s|hoofdletter ringel-s',
      vi: 'chữ s sắc thường|chữ s sắc hoa',
      ar: 'حرف s حاد صغير|حرف s حاد كبير',

      en: 'eszett|sharp s|german|double s',
      ru: 'эсцет|немецкая|двойная с',
      pl: 'eszett|niemiecki|podwójne s',
      fr: 'eszett|allemand|double s',
      de: 'Eszett|scharfes s|Doppel s',
      es: 'eszett|alemán|doble s',
      pt: 'eszett|alemão|s duplo',
      it: 'eszett|tedesco|doppia s',
      ro: 'eszett|germană|s dublu',
      he: 'אסצט|גרמנית|אס כפולה',
    },
    description: {
      tr: 'Almanca Eszett harfi: küçük ß ve büyük ẞ.',
      nl: 'Duitse letter Eszett of ringel-s: kleine ß en hoofdletter ẞ.',
      vi: 'Chữ Eszett tiếng Đức: chữ thường ß và chữ hoa ẞ.',
      ar: 'حرف إسْتسِت الألماني: ß صغير وẞ كبير.',

      en: 'A German letter called Eszett or sharp S, with lowercase ß and uppercase ẞ forms.',
      ru: 'Немецкая буква эсцет: строчная ß и прописная ẞ.',
      pl: 'Niemiecka litera eszett: mała ß i wielka ẞ.',
      fr: 'Lettre allemande appelée eszett : minuscule ß et majuscule ẞ.',
      de: 'Deutscher Buchstabe Eszett: kleines ß und großes ẞ.',
      es: 'Letra alemana llamada eszett: minúscula ß y mayúscula ẞ.',
      pt: 'Letra alemã chamada eszett: minúscula ß e maiúscula ẞ.',
      it: 'Lettera tedesca eszett: minuscola ß e maiuscola ẞ.',
      ro: 'Literă germană numită eszett: minusculă ß și majusculă ẞ.',
      he: 'אות גרמנית הנקראת אסצט: צורה קטנה ß וצורה גדולה ẞ.',
    },
  },
  {
    symbols: ['[', ']', '{', '}'],
    terms: {
      tr: 'sol köşeli parantez|sağ köşeli parantez|sol süslü parantez|sağ süslü parantez',
      nl: 'vierkante haak openen|vierkante haak sluiten|accolade openen|accolade sluiten',
      vi: 'ngoặc vuông trái|ngoặc vuông phải|ngoặc nhọn trái|ngoặc nhọn phải',
      ar: 'قوس مربع أيسر|قوس مربع أيمن|قوس معقوف أيسر|قوس معقوف أيمن',

      en: 'bracket|brace|code|group',
      ru: 'скобка|код|группа|массив',
      pl: 'nawias|kod|grupa',
      fr: 'crochet|accolade|code|groupe',
      de: 'Klammer|Code|Gruppe',
      es: 'corchete|llave|código|grupo',
      pt: 'colchete|chave|código|grupo',
      it: 'parentesi|codice|gruppo',
      ro: 'paranteză|cod|grup',
      he: 'סוגריים|קוד|קבוצה',
    },
    description: {
      tr: 'Metin, formül veya kodu gruplar. Köşeli ve süslü parantezlerin işlevleri farklıdır.',
      nl: 'Groepeert tekst, formules of code. Vierkante haken en accolades hebben verschillende functies.',
      vi: 'Nhóm văn bản, công thức hoặc mã. Ngoặc vuông và ngoặc nhọn có công dụng khác nhau.',
      ar: 'يجمع نصًا أو صيغة أو كودًا. للأقواس المربعة والمعقوفة وظائف مختلفة.',

      en: 'Paired brackets group text, mathematical expressions or code. Square and curly brackets have distinct uses.',
      ru: 'Парные скобки группируют текст, формулы или код. Квадратные и фигурные скобки имеют разные назначения.',
      pl: 'Nawiasy grupują tekst, wyrażenia lub kod. Kwadratowe i klamrowe mają różne zastosowania.',
      fr: 'Les crochets et accolades regroupent du texte, des expressions ou du code, avec des usages distincts.',
      de: 'Klammern gruppieren Text, Formeln oder Code. Eckige und geschweifte Klammern haben verschiedene Aufgaben.',
      es: 'Los corchetes y llaves agrupan texto, expresiones o código con funciones distintas.',
      pt: 'Colchetes e chaves agrupam texto, expressões ou código com funções distintas.',
      it: 'Le parentesi raggruppano testo, formule o codice. Quadre e graffe hanno usi diversi.',
      ro: 'Parantezele grupează text, formule sau cod. Cele pătrate și acoladele au utilizări diferite.',
      he: 'סוגריים מקבצים טקסט, ביטויים או קוד. לסוגריים מרובעים ומסולסלים שימושים שונים.',
    },
  },
  {
    symbols: ['…'],
    terms: {
      tr: 'üç nokta',
      nl: 'beletselteken',
      vi: 'dấu ba chấm',
      ar: 'علامة الحذف',

      en: 'ellipsis|three dots',
      ru: 'многоточие|три точки|продолжение',
      pl: 'wielokropek|trzy kropki',
      fr: 'points de suspension|trois points',
      de: 'Auslassungspunkte|drei Punkte',
      es: 'puntos suspensivos|tres puntos',
      pt: 'reticências|três pontos',
      it: 'puntini di sospensione|tre punti',
      ro: 'puncte de suspensie|trei puncte',
      he: 'שלוש נקודות|השמטה',
    },
    description: {
      tr: 'Atlanan metin, duraklama veya tamamlanmamış düşünceyi gösterir.',
      nl: 'Geeft weggelaten tekst, een pauze of onafgemaakte gedachte aan.',
      vi: 'Biểu thị phần bỏ lược, ngừng hoặc ý chưa hoàn tất.',
      ar: 'يدل على نص محذوف أو وقفة أو فكرة غير مكتملة.',

      en: 'Marks omitted text, a pause or an unfinished thought.',
      ru: 'Обозначает пропуск текста, паузу или незаконченную мысль.',
      pl: 'Oznacza pominięty tekst, pauzę lub niedokończoną myśl.',
      fr: 'Marque une omission, une pause ou une pensée inachevée.',
      de: 'Kennzeichnet ausgelassenen Text, eine Pause oder einen unvollendeten Gedanken.',
      es: 'Indica texto omitido, una pausa o una idea incompleta.',
      pt: 'Indica texto omitido, pausa ou pensamento incompleto.',
      it: 'Indica testo omesso, pausa o pensiero incompleto.',
      ro: 'Marchează text omis, o pauză sau un gând neterminat.',
      he: 'מציין השמטה, הפסקה או מחשבה לא גמורה.',
    },
  },
  {
    symbols: [' '],
    terms: {
      tr: ' ',
      nl: ' ',
      vi: ' ',
      ar: ' ',

      en: 'nbsp|nonbreaking space|no break',
      ru: 'неразрывный пробел|без разрыва|склейка',
      pl: 'spacja niełamliwa|bez podziału',
      fr: 'espace insécable|sans coupure',
      de: 'geschütztes Leerzeichen|kein Umbruch',
      es: 'espacio inseparable|sin salto',
      pt: 'espaço inseparável|sem quebra',
      it: 'spazio unificatore|senza interruzione',
      ro: 'spațiu inseparabil|fără întrerupere',
      he: 'רווח קשיח|ללא שבירה',
    },
    description: {
      tr: 'Yanındaki sözcükleri veya sayıları aynı satırda tutan boşluk.',
      nl: 'Spatie die aangrenzende woorden of getallen op dezelfde regel houdt.',
      vi: 'Dấu cách giữ các từ hoặc số liền kề trên cùng dòng.',
      ar: 'مسافة تُبقي الكلمات أو الأرقام المجاورة في السطر نفسه.',

      en: 'A space that keeps adjacent words or numbers on the same line.',
      ru: 'Пробел, который не позволяет перенести соседние слова или числа на разные строки.',
      pl: 'Spacja utrzymująca sąsiednie słowa lub liczby w jednym wierszu.',
      fr: 'Espace maintenant les mots ou nombres voisins sur la même ligne.',
      de: 'Leerzeichen, das benachbarte Wörter oder Zahlen in derselben Zeile hält.',
      es: 'Espacio que mantiene palabras o números vecinos en la misma línea.',
      pt: 'Espaço que mantém palavras ou números vizinhos na mesma linha.',
      it: 'Spazio che mantiene parole o numeri adiacenti sulla stessa riga.',
      ro: 'Spațiu care păstrează cuvintele sau numerele vecine pe același rând.',
      he: 'רווח המשאיר מילים או מספרים סמוכים באותה שורה.',
    },
  },
  {
    symbols: ['‰'],
    terms: {
      tr: 'binde',
      nl: 'promille',
      vi: 'phần nghìn',
      ar: 'بالألف',

      en: 'per mille|per thousand|alcohol',
      ru: 'промилле|тысячная|алкоголь',
      pl: 'promil|tysięczna',
      fr: 'pour mille|alcool',
      de: 'Promille|Tausendstel',
      es: 'por mil|alcohol',
      pt: 'por mil|álcool',
      it: 'per mille|alcol',
      ro: 'la mie|alcool',
      he: 'פרומיל|אלפית',
    },
    description: {
      tr: 'Binde bir: 1‰, %0,1 eder.',
      nl: 'Een duizendste: 1‰ is 0,1%.',
      vi: 'Một phần nghìn: 1‰ bằng 0,1%.',
      ar: 'جزء من ألف: 1‰ يساوي 0.1%.',

      en: 'Parts per thousand: 1‰ equals 0.1%.',
      ru: 'Доли от тысячи: 1‰ равен 0,1%.',
      pl: 'Części tysięczne: 1‰ to 0,1%.',
      fr: 'Parties pour mille : 1‰ vaut 0,1%.',
      de: 'Tausendstel: 1‰ entspricht 0,1%.',
      es: 'Partes por mil: 1‰ equivale al 0,1%.',
      pt: 'Partes por mil: 1‰ equivale a 0,1%.',
      it: 'Parti per mille: 1‰ equivale allo 0,1%.',
      ro: 'Părți la mie: 1‰ este egal cu 0,1%.',
      he: 'חלקים מאלף: 1‰ שווה ל־0.1%.',
    },
  },
  {
    symbols: ['°'],
    terms: {
      tr: 'derece',
      nl: 'graad',
      vi: 'độ',
      ar: 'درجة',

      en: 'degree|temperature|angle|weather',
      ru: 'градус|температура|угол|погода',
      pl: 'stopień|temperatura|kąt',
      fr: 'degré|température|angle',
      de: 'Grad|Temperatur|Winkel',
      es: 'grado|temperatura|ángulo',
      pt: 'grau|temperatura|ângulo',
      it: 'grado|temperatura|angolo',
      ro: 'grad|temperatură|unghi',
      he: 'מעלה|טמפרטורה|זווית',
    },
    description: {
      tr: 'Açılar ve °C gibi sıcaklık birimlerinde kullanılır.',
      nl: 'Voor hoeken en temperatuureenheden zoals °C.',
      vi: 'Dùng cho góc và đơn vị nhiệt độ như °C.',
      ar: 'للزوايا ووحدات الحرارة مثل °C.',

      en: 'Used for angles and in temperature units such as °C.',
      ru: 'Обозначает углы и входит в обозначения температуры, например °C.',
      pl: 'Oznacza kąty i występuje w jednostkach temperatury, np. °C.',
      fr: 'Indique les angles et entre dans les unités de température, comme °C.',
      de: 'Für Winkel und in Temperatureinheiten wie °C.',
      es: 'Se usa en ángulos y unidades de temperatura como °C.',
      pt: 'Usado em ângulos e unidades de temperatura como °C.',
      it: 'Usato per angoli e unità di temperatura come °C.',
      ro: 'Folosit pentru unghiuri și unități de temperatură precum °C.',
      he: 'משמש לזוויות וביחידות טמפרטורה כגון °C.',
    },
  },
  {
    symbols: ['⌀'],
    terms: {
      tr: 'çap',
      nl: 'diameter',
      vi: 'đường kính',
      ar: 'قطر',

      en: 'diameter|circle|engineering',
      ru: 'диаметр|круг|чертёж',
      pl: 'średnica|okrąg',
      fr: 'diamètre|cercle',
      de: 'Durchmesser|Kreis',
      es: 'diámetro|círculo',
      pt: 'diâmetro|círculo',
      it: 'diametro|cerchio',
      ro: 'diametru|cerc',
      he: 'קוטר|מעגל',
    },
    description: {
      tr: 'Teknik çizimlerde dairesel nesnenin çapını gösterir.',
      nl: 'Geeft de diameter van een rond object aan in technische tekeningen.',
      vi: 'Chỉ đường kính vật tròn trong bản vẽ kỹ thuật.',
      ar: 'يشير إلى قطر جسم دائري في الرسومات الفنية.',

      en: 'Indicates the diameter of a circular object in technical drawings.',
      ru: 'Обозначает диаметр круглой детали на технических чертежах.',
      pl: 'Oznacza średnicę okrągłego obiektu na rysunkach technicznych.',
      fr: 'Indique le diamètre d’un objet circulaire sur un dessin technique.',
      de: 'Bezeichnet den Durchmesser eines runden Objekts in technischen Zeichnungen.',
      es: 'Indica el diámetro de un objeto circular en dibujos técnicos.',
      pt: 'Indica o diâmetro de um objeto circular em desenhos técnicos.',
      it: 'Indica il diametro di un oggetto circolare nei disegni tecnici.',
      ro: 'Indică diametrul unui obiect circular în desene tehnice.',
      he: 'מציין קוטר של עצם עגול בשרטוטים טכניים.',
    },
  },
  {
    symbols: ['✓'],
    terms: {
      tr: 'onay işareti',
      nl: 'vinkje',
      vi: 'dấu kiểm',
      ar: 'علامة صح',

      en: 'check|tick|done|yes|success',
      ru: 'галочка|готово|да|успех|птичка',
      pl: 'ptaszek|gotowe|tak',
      fr: 'coche|fait|oui',
      de: 'Häkchen|fertig|ja',
      es: 'marca|hecho|sí',
      pt: 'visto|feito|sim',
      it: 'spunta|fatto|sì',
      ro: 'bifă|gata|da',
      he: 'וי|בוצע|כן',
    },
    description: {
      tr: 'Tamamlanma, doğruluk veya onay gösterir.',
      nl: 'Geeft voltooiing, juistheid of goedkeuring aan.',
      vi: 'Biểu thị hoàn tất, đúng hoặc chấp thuận.',
      ar: 'يدل على الإكمال أو الصحة أو الموافقة.',

      en: 'A check mark indicates completion, correctness or approval.',
      ru: 'Галочка отмечает выполнение, правильность или подтверждение.',
      pl: 'Znacznik oznacza wykonanie, poprawność lub akceptację.',
      fr: 'Une coche indique l’achèvement, la validité ou l’approbation.',
      de: 'Ein Häkchen kennzeichnet Erledigung, Richtigkeit oder Zustimmung.',
      es: 'Una marca indica finalización, corrección o aprobación.',
      pt: 'Um visto indica conclusão, correção ou aprovação.',
      it: 'Una spunta indica completamento, correttezza o approvazione.',
      ro: 'O bifă indică finalizarea, corectitudinea sau aprobarea.',
      he: 'סימן וי מציין השלמה, נכונות או אישור.',
    },
  },
  {
    symbols: ['•'],
    terms: {
      tr: 'madde imi',
      nl: 'opsommingsteken',
      vi: 'dấu đầu dòng',
      ar: 'علامة تعداد',

      en: 'bullet|list|dot',
      ru: 'маркер|список|точка',
      pl: 'punktor|lista|kropka',
      fr: 'puce|liste|point',
      de: 'Aufzählung|Liste|Punkt',
      es: 'viñeta|lista|punto',
      pt: 'marcador|lista|ponto',
      it: 'punto elenco|lista',
      ro: 'marcator|listă|punct',
      he: 'תבליט|רשימה|נקודה',
    },
    description: {
      tr: 'Sırasız listedeki bir öğeyi başlatır.',
      nl: 'Markeert een onderdeel van een ongeordende lijst.',
      vi: 'Đánh dấu mục trong danh sách không thứ tự.',
      ar: 'يبدأ عنصرًا في قائمة غير مرتبة.',

      en: 'A bullet introduces an item in an unordered list.',
      ru: 'Маркер выделяет пункт ненумерованного списка.',
      pl: 'Punktor rozpoczyna element listy nienumerowanej.',
      fr: 'Une puce introduit un élément de liste non numérotée.',
      de: 'Ein Aufzählungszeichen beginnt einen Eintrag einer ungeordneten Liste.',
      es: 'Una viñeta introduce un elemento en una lista sin numerar.',
      pt: 'Um marcador inicia um item de lista não numerada.',
      it: 'Un punto elenco introduce una voce di una lista non numerata.',
      ro: 'Un marcator introduce un element al unei liste nenumerotate.',
      he: 'תבליט פותח פריט ברשימה לא ממוספרת.',
    },
  },
  {
    symbols: ['§'],
    terms: {
      tr: 'bölüm işareti',
      nl: 'paragraafteken',
      vi: 'dấu mục',
      ar: 'علامة القسم',

      en: 'section|paragraph|law',
      ru: 'параграф|раздел|закон',
      pl: 'paragraf|prawo',
      fr: 'paragraphe|section|loi',
      de: 'Paragraf|Abschnitt|Gesetz',
      es: 'párrafo|sección|ley',
      pt: 'parágrafo|secção|lei',
      it: 'paragrafo|sezione|legge',
      ro: 'paragraf|secțiune|lege',
      he: 'סעיף|חוק',
    },
    description: {
      tr: 'Özellikle hukuk ve başvuru metinlerinde numaralı bölümü belirtir.',
      nl: 'Markeert een genummerde paragraaf, vaak in juridische teksten.',
      vi: 'Đánh dấu mục đánh số, thường trong văn bản pháp lý.',
      ar: 'يشير إلى قسم مرقّم، خصوصًا في النصوص القانونية والمرجعية.',

      en: 'Marks a numbered section, often in legal or reference texts.',
      ru: 'Обозначает нумерованный раздел, часто в законах и справочных текстах.',
      pl: 'Oznacza numerowany paragraf, często w tekstach prawnych.',
      fr: 'Indique une section numérotée, souvent dans les textes juridiques.',
      de: 'Kennzeichnet einen nummerierten Abschnitt, häufig in Gesetzestexten.',
      es: 'Marca una sección numerada, a menudo en textos jurídicos.',
      pt: 'Marca uma secção numerada, frequentemente em textos jurídicos.',
      it: 'Indica una sezione numerata, spesso in testi giuridici.',
      ro: 'Marchează o secțiune numerotată, adesea în texte juridice.',
      he: 'מציין סעיף ממוספר, לרוב בטקסטים משפטיים או בספרי עיון.',
    },
  },
  {
    symbols: ['′', '″'],
    terms: {
      tr: 'asal işareti|çift asal işareti',
      nl: 'priem|dubbele priem',
      vi: 'dấu phẩy trên|dấu phẩy trên kép',
      ar: 'علامة أولية|علامة أولية مزدوجة',

      en: 'prime|feet|inches|minutes|seconds',
      ru: 'штрих|фут|дюйм|минута|секунда',
      pl: 'prim|stopy|cale',
      fr: 'prime|pied|pouce',
      de: 'Strich|Fuß|Zoll',
      es: 'prima|pie|pulgada',
      pt: 'primo|pé|polegada',
      it: 'primo|piede|pollice',
      ro: 'prim|picior|țol',
      he: 'גרש|רגל|אינץ',
    },
    description: {
      tr: 'Ayak, inç, yay dakikası, yay saniyesi veya matematikte türevleri belirtir.',
      nl: 'Voor voet, inch, boogminuten, boogseconden of afgeleiden in de wiskunde.',
      vi: 'Dùng cho foot, inch, phút cung, giây cung hoặc đạo hàm.',
      ar: 'للقدم والبوصة والدقائق والثواني القوسية أو المشتقات الرياضية.',

      en: 'Prime and double prime denote feet and inches, arcminutes and arcseconds, or derivatives in mathematics.',
      ru: 'Штрих и двойной штрих обозначают футы и дюймы, угловые минуты и секунды или производные.',
      pl: 'Prim i bis oznaczają stopy i cale, minuty i sekundy kątowe lub pochodne.',
      fr: 'Prime et double prime notent les pieds et pouces, les minutes et secondes d’arc ou les dérivées.',
      de: 'Strich und Doppelstrich bezeichnen Fuß und Zoll, Winkelminuten und -sekunden oder Ableitungen.',
      es: 'Prima y doble prima indican pies y pulgadas, minutos y segundos de arco o derivadas.',
      pt: 'Primo e duplo primo indicam pés e polegadas, minutos e segundos de arco ou derivadas.',
      it: 'Primo e doppio primo indicano piedi e pollici, minuti e secondi d’arco o derivate.',
      ro: 'Prim și dublu prim indică picioare și țoli, minute și secunde de arc sau derivate.',
      he: 'גרש וגרש כפול מציינים רגל ואינץ, דקות ושניות קשת או נגזרות.',
    },
  },
  {
    symbols: ['¡', '¿'],
    terms: {
      tr: 'ters ünlem|ters soru işareti',
      nl: 'omgekeerd uitroepteken|omgekeerd vraagteken',
      vi: 'dấu chấm than ngược|dấu hỏi ngược',
      ar: 'علامة تعجب مقلوبة|علامة استفهام مقلوبة',

      en: 'inverted|spanish|question|exclamation',
      ru: 'перевёрнутый|испанский|вопрос|восклицание',
      pl: 'odwrócony|hiszpański|pytanie',
      fr: 'inversé|espagnol|question',
      de: 'umgekehrt|Spanisch|Frage',
      es: 'invertido|español|pregunta|exclamación',
      pt: 'invertido|espanhol|pergunta',
      it: 'capovolto|spagnolo|domanda',
      ro: 'inversat|spaniolă|întrebare',
      he: 'הפוך|ספרדית|שאלה',
    },
    description: {
      tr: 'İspanyolcada soru veya ünlemin başına konur; sonunda ? veya ! bulunur.',
      nl: 'Opent in het Spaans een vraag of uitroep vóór de afsluitende ? of !.',
      vi: 'Mở câu hỏi hoặc cảm thán tiếng Tây Ban Nha trước ? hoặc ! kết thúc.',
      ar: 'يفتتح السؤال أو التعجب بالإسبانية قبل ? أو ! الختامية.',

      en: 'In Spanish, opens a question or exclamation before the closing ? or !.',
      ru: 'В испанском открывает вопрос или восклицание перед завершающим ? или !.',
      pl: 'W hiszpańskim otwiera pytanie lub wykrzyknienie przed końcowym ? lub !.',
      fr: 'En espagnol, ouvre une question ou une exclamation avant le ? ou ! final.',
      de: 'Eröffnet im Spanischen eine Frage oder einen Ausruf vor dem abschließenden ? oder !.',
      es: 'Abre una pregunta o exclamación antes del signo final ? o !.',
      pt: 'Em espanhol, abre uma pergunta ou exclamação antes do ? ou ! final.',
      it: 'In spagnolo apre una domanda o esclamazione prima del ? o ! finale.',
      ro: 'În spaniolă deschide o întrebare sau exclamație înainte de ? sau ! final.',
      he: 'בספרדית פותח שאלה או קריאה לפני סימן הסיום ? או !.',
    },
  },
  {
    symbols: ['#'],
    terms: {
      tr: 'numara işareti',
      nl: 'hekje',
      vi: 'dấu thăng',
      ar: 'علامة الرقم',

      en: 'hash|hashtag|number|pound',
      ru: 'решётка|хештег|номер',
      pl: 'kratka|hasztag|numer',
      fr: 'croisillon|hashtag|numéro',
      de: 'Raute|Hashtag|Nummer',
      es: 'almohadilla|etiqueta|número',
      pt: 'cerquilha|hashtag|número',
      it: 'cancelletto|hashtag|numero',
      ro: 'diez|hashtag|număr',
      he: 'סולמית|האשטאג|מספר',
    },
    description: {
      tr: 'Etiketler, numaralandırma ve programlama sözdiziminde kullanılır.',
      nl: 'Voor hashtags, nummering en programmeersyntaxis.',
      vi: 'Dùng cho hashtag, đánh số và cú pháp lập trình.',
      ar: 'للوسوم والترقيم وصياغة لغات البرمجة.',

      en: 'Used for hashtags, numbering and syntax in programming languages.',
      ru: 'Используется в хештегах, нумерации и синтаксисе языков программирования.',
      pl: 'Używany w hasztagach, numeracji i składni języków programowania.',
      fr: 'Utilisé dans les hashtags, la numérotation et les langages de programmation.',
      de: 'Für Hashtags, Nummerierungen und Programmiersyntax.',
      es: 'Se usa en etiquetas, numeración y sintaxis de programación.',
      pt: 'Usado em hashtags, numeração e sintaxe de programação.',
      it: 'Usato per hashtag, numerazione e sintassi di programmazione.',
      ro: 'Folosit în hashtaguri, numerotare și sintaxa limbajelor de programare.',
      he: 'משמש להאשטאגים, מספור ותחביר בשפות תכנות.',
    },
  },
  {
    symbols: ['©'],
    terms: {
      tr: 'telif hakkı',
      nl: 'auteursrecht',
      vi: 'bản quyền',
      ar: 'حقوق النشر',

      en: 'copyright|registered|trademark|brand',
      ru: 'копирайт|авторство|товарный знак|бренд',
      pl: 'prawo autorskie|znak towarowy',
      fr: 'droit d’auteur|marque déposée',
      de: 'Urheberrecht|Marke',
      es: 'derechos de autor|marca registrada',
      pt: 'direitos autorais|marca registada',
      it: 'diritto d’autore|marchio',
      ro: 'drepturi de autor|marcă',
      he: 'זכויות יוצרים|סימן מסחר',
    },
    description: {
      tr: 'Telif hakkı sahibini belirten bildirimlerde kullanılan simge.',
      nl: 'Symbool in vermeldingen van de auteursrechthebbende.',
      vi: 'Ký hiệu trong thông báo xác định chủ sở hữu bản quyền.',
      ar: 'رمز في الإشعارات التي تحدّد صاحب حقوق النشر.',

      en: 'A copyright symbol used in notices identifying the copyright holder.',
      ru: 'Знак авторского права. Используется в уведомлениях с указанием правообладателя.',
      pl: 'Symbol prawa autorskiego. Używany w informacjach wskazujących właściciela praw.',
      fr: 'Symbole du droit d’auteur. Utilisé dans les mentions indiquant le titulaire des droits.',
      de: 'Urheberrechtszeichen. Wird in Hinweisen verwendet, die den Rechteinhaber nennen.',
      es: 'Símbolo de derechos de autor. Se usa en avisos que identifican al titular de los derechos.',
      pt: 'Símbolo de direitos de autor. Usado em avisos que identificam o titular dos direitos.',
      it: 'Simbolo del diritto d’autore. Usato nelle indicazioni che identificano il titolare dei diritti.',
      ro: 'Simbol al drepturilor de autor. Folosit în mențiuni care identifică titularul drepturilor.',
      he: 'סימן זכויות יוצרים. משמש בהודעות המציינות את בעל הזכויות.',
    },
  },
  {
    symbols: ['®'],
    terms: {
      tr: 'tescilli marka',
      nl: 'geregistreerd handelsmerk',
      vi: 'nhãn hiệu đã đăng ký',
      ar: 'علامة تجارية مسجلة',

      en: 'copyright|registered|trademark|brand',
      ru: 'копирайт|авторство|товарный знак|бренд',
      pl: 'prawo autorskie|znak towarowy',
      fr: 'droit d’auteur|marque déposée',
      de: 'Urheberrecht|Marke',
      es: 'derechos de autor|marca registrada',
      pt: 'direitos autorais|marca registada',
      it: 'diritto d’autore|marchio',
      ro: 'drepturi de autor|marcă',
      he: 'זכויות יוצרים|סימן מסחר',
    },
    description: {
      tr: 'Yanındaki markanın tescil edildiğini gösterir.',
      nl: 'Geeft aan dat het bijbehorende handelsmerk geregistreerd is.',
      vi: 'Cho biết nhãn hiệu đi kèm đã đăng ký.',
      ar: 'يشير إلى أن العلامة المرافقة مسجلة.',

      en: 'A registered trademark symbol. Indicates that the accompanying mark is registered.',
      ru: 'Знак зарегистрированного товарного знака. Указывает на регистрацию обозначения, рядом с которым стоит.',
      pl: 'Symbol zarejestrowanego znaku towarowego. Wskazuje, że oznaczenie, któremu towarzyszy, jest zarejestrowane.',
      fr: 'Symbole de marque enregistrée. Indique que la marque qui l’accompagne est enregistrée.',
      de: 'Symbol einer eingetragenen Marke. Zeigt an, dass das begleitende Kennzeichen registriert ist.',
      es: 'Símbolo de marca registrada. Indica que la marca a la que acompaña está registrada.',
      pt: 'Símbolo de marca registada. Indica que a marca que acompanha está registada.',
      it: 'Simbolo di marchio registrato. Indica che il marchio che accompagna è registrato.',
      ro: 'Simbol al unei mărci înregistrate. Indică faptul că marca alăturată este înregistrată.',
      he: 'סימן מסחר רשום. מציין שהסימן המסחרי שלצדו רשום.',
    },
  },
  {
    symbols: ['™'],
    terms: {
      tr: 'ticari marka',
      nl: 'handelsmerk',
      vi: 'nhãn hiệu',
      ar: 'علامة تجارية',

      en: 'copyright|registered|trademark|brand',
      ru: 'копирайт|авторство|товарный знак|бренд',
      pl: 'prawo autorskie|znak towarowy',
      fr: 'droit d’auteur|marque déposée',
      de: 'Urheberrecht|Marke',
      es: 'derechos de autor|marca registrada',
      pt: 'direitos autorais|marca registada',
      it: 'diritto d’autore|marchio',
      ro: 'drepturi de autor|marcă',
      he: 'זכויות יוצרים|סימן מסחר',
    },
    description: {
      tr: 'Adın veya logonun ticari marka olarak kullanıldığını belirtir; tek başına tescil anlamına gelmez.',
      nl: 'Geeft gebruik als handelsmerk aan; betekent op zichzelf geen registratie.',
      vi: 'Cho biết tên hoặc logo được dùng làm nhãn hiệu; không tự biểu thị đã đăng ký.',
      ar: 'يدل على استخدام الاسم أو الشعار كعلامة تجارية؛ ولا يعني التسجيل بمفرده.',

      en: 'A trademark symbol. Indicates that a name or logo is used as a trademark; it does not by itself indicate registration.',
      ru: 'Обозначение товарного знака. Показывает, что название или логотип используется как товарный знак; само по себе не указывает на регистрацию.',
      pl: 'Symbol znaku towarowego. Oznacza, że nazwa lub logo jest używane jako znak towarowy; sam w sobie nie wskazuje na rejestrację.',
      fr: 'Symbole de marque commerciale. Indique qu’un nom ou un logo est utilisé comme marque, sans indiquer à lui seul son enregistrement.',
      de: 'Markenzeichen. Kennzeichnet einen Namen oder ein Logo als Marke, weist aber allein nicht auf eine Registrierung hin.',
      es: 'Símbolo de marca comercial. Indica que un nombre o logotipo se usa como marca; por sí solo no indica que esté registrada.',
      pt: 'Símbolo de marca comercial. Indica que um nome ou logótipo é usado como marca; por si só não indica registo.',
      it: 'Simbolo di marchio commerciale. Indica che un nome o logo è usato come marchio; da solo non ne indica la registrazione.',
      ro: 'Simbol de marcă comercială. Indică folosirea unui nume sau logo ca marcă; singur nu indică înregistrarea.',
      he: 'סימן מסחר. מציין ששם או לוגו משמש כסימן מסחרי; כשלעצמו אינו מעיד על רישום.',
    },
  },
  {
    symbols: [''],
    terms: {
      tr: 'Apple logosu',
      nl: 'Apple-logo',
      vi: 'biểu trưng Apple',
      ar: 'شعار Apple',

      en: 'apple|logo|mac',
      ru: 'яблоко|логотип|мак',
      pl: 'apple|logo|jabłko',
      fr: 'apple|logo|pomme',
      de: 'Apple|Logo|Apfel',
      es: 'apple|logotipo|manzana',
      pt: 'apple|logótipo|maçã',
      it: 'apple|logo|mela',
      ro: 'apple|siglă|măr',
      he: 'אפל|לוגו|תפוח',
    },
    description: {
      tr: 'Unicode özel kullanım alanındaki Apple logosu; görünümü yazı tipine bağlıdır.',
      nl: 'Apple-logo in het Unicode-privégebruiksgebied; weergave hangt af van het lettertype.',
      vi: 'Logo Apple trong vùng dùng riêng Unicode; hiển thị tùy phông chữ.',
      ar: 'شعار Apple في منطقة الاستخدام الخاص في Unicode؛ يعتمد عرضه على الخط.',

      en: 'Apple logo in the Unicode private-use area, rendering depends on the font.',
      ru: 'Логотип Apple в области частного использования Unicode. Отображение зависит от шрифта.',
      pl: 'Logo Apple w obszarze prywatnego użytku Unicode, zależne od czcionki.',
      fr: 'Logo Apple dans la zone privée Unicode, dont l’affichage dépend de la police.',
      de: 'Apple-Logo im privaten Unicode-Bereich, dessen Darstellung von der Schrift abhängt.',
      es: 'Logotipo de Apple en el área privada de Unicode, dependiente de la fuente.',
      pt: 'Logótipo da Apple na área privada Unicode, dependente do tipo de letra.',
      it: 'Logo Apple nell’area privata Unicode, la cui resa dipende dal font.',
      ro: 'Sigla Apple în zona privată Unicode, afișată în funcție de font.',
      he: 'לוגו Apple באזור השימוש הפרטי של Unicode; התצוגה תלויה בגופן.',
    },
  },
];

// Symbol-specific definitions take precedence over family descriptions.
const mathDefinitions = [
  [
    '≈',
    'Indicates approximate equality: two values are close, but need not be equal.',
    'Приблизительное равенство: величины близки, но не обязательно равны.',
    'Oznacza przybliżoną równość dwóch wartości.',
    'Indique une égalité approximative entre deux valeurs.',
    'Bezeichnet die ungefähre Gleichheit zweier Werte.',
    'Indica igualdad aproximada entre dos valores.',
    'Indica igualdade aproximada entre dois valores.',
    'Indica uguaglianza approssimata tra due valori.',
    'Indică egalitatea aproximativă a două valori.',
    'מציין שוויון בקירוב בין שני ערכים.',
  ],
  [
    '≠',
    'Indicates that two values are not equal.',
    'Обозначает, что две величины не равны.',
    'Oznacza, że dwie wartości nie są równe.',
    'Indique que deux valeurs ne sont pas égales.',
    'Zeigt an, dass zwei Werte nicht gleich sind.',
    'Indica que dos valores no son iguales.',
    'Indica que dois valores não são iguais.',
    'Indica che due valori non sono uguali.',
    'Indică faptul că două valori nu sunt egale.',
    'מציין ששני ערכים אינם שווים.',
  ],
  [
    '±',
    'Means plus or minus; used for two possible values or a measurement tolerance.',
    'Плюс-минус: два возможных значения или допустимая погрешность измерения.',
    'Plus minus: dwie możliwe wartości lub tolerancja pomiaru.',
    'Plus ou moins : deux valeurs possibles ou une tolérance de mesure.',
    'Plusminus: zwei mögliche Werte oder eine Messtoleranz.',
    'Más o menos: dos valores posibles o una tolerancia de medida.',
    'Mais ou menos: dois valores possíveis ou uma tolerância de medição.',
    'Più o meno: due valori possibili o una tolleranza di misura.',
    'Plus sau minus: două valori posibile sau o toleranță de măsurare.',
    'פלוס מינוס: שני ערכים אפשריים או סטיית מדידה.',
  ],
  [
    '−',
    'A mathematical minus for subtraction and negative numbers, distinct from a hyphen or dash.',
    'Математический минус для вычитания и отрицательных чисел. Отличается от дефиса и тире.',
    'Minus matematyczny do odejmowania i liczb ujemnych, odmienny od łącznika.',
    'Signe moins pour la soustraction et les nombres négatifs, distinct du tiret.',
    'Mathematisches Minus für Subtraktion und negative Zahlen, kein Bindestrich.',
    'Signo menos para restas y números negativos, distinto del guion.',
    'Sinal de menos para subtração e números negativos, distinto do hífen.',
    'Segno meno per sottrazioni e numeri negativi, distinto dal trattino.',
    'Semn minus pentru scădere și numere negative, diferit de cratimă.',
    'סימן מינוס לחיסור ולמספרים שליליים, שונה ממקף.',
  ],
  [
    '×',
    'A multiplication sign, also used between dimensions such as 10 × 20.',
    'Знак умножения. Также разделяет размеры, например 10 × 20.',
    'Znak mnożenia, także między wymiarami, np. 10 × 20.',
    'Signe de multiplication, aussi entre les dimensions, comme 10 × 20.',
    'Multiplikationszeichen, auch zwischen Maßangaben wie 10 × 20.',
    'Signo de multiplicación, también entre dimensiones como 10 × 20.',
    'Sinal de multiplicação, também entre dimensões como 10 × 20.',
    'Segno di moltiplicazione, anche tra dimensioni come 10 × 20.',
    'Semn de înmulțire, folosit și între dimensiuni precum 10 × 20.',
    'סימן כפל, המשמש גם בין מידות כגון 10 × 20.',
  ],
  [
    '·',
    'A centered dot used for multiplication or as a separator in text.',
    'Точка на середине строки: знак умножения или разделитель в тексте.',
    'Kropka środkowa używana do mnożenia lub rozdzielania tekstu.',
    'Point médian utilisé pour la multiplication ou comme séparateur.',
    'Mittiger Punkt als Multiplikationszeichen oder Texttrenner.',
    'Punto centrado para multiplicación o separación de texto.',
    'Ponto centrado para multiplicação ou separação de texto.',
    'Punto mediano per moltiplicazione o separazione del testo.',
    'Punct median pentru înmulțire sau separarea textului.',
    'נקודה אמצעית לכפל או להפרדת טקסט.',
  ],
  [
    '∞',
    'Infinity expresses an unbounded quantity or a process without end.',
    'Бесконечность обозначает неограниченную величину или процесс без конца.',
    'Nieskończoność oznacza nieograniczoną wielkość lub proces bez końca.',
    'L’infini exprime une quantité illimitée ou un processus sans fin.',
    'Unendlichkeit bezeichnet eine unbegrenzte Größe oder einen endlosen Vorgang.',
    'El infinito expresa una cantidad ilimitada o un proceso sin fin.',
    'O infinito expressa uma quantidade ilimitada ou um processo sem fim.',
    'L’infinito esprime una quantità illimitata o un processo senza fine.',
    'Infinitul exprimă o cantitate nelimitată sau un proces fără sfârșit.',
    'אינסוף מציין כמות בלתי מוגבלת או תהליך ללא סוף.',
  ],
] as const;
const definitionLocales: Locale[] = [
  'en',
  'ru',
  'pl',
  'fr',
  'de',
  'es',
  'pt',
  'it',
  'ro',
  'he',
];
const additionalDefinitions = {
  '≈': {
    tr: 'İki değerin yakın, fakat mutlaka eşit olmadığını gösterir.',
    nl: 'Twee waarden liggen dicht bij elkaar, maar zijn niet noodzakelijk gelijk.',
    vi: 'Hai giá trị gần nhau nhưng không nhất thiết bằng nhau.',
    ar: 'قيمتان متقاربتان لكنهما ليستا بالضرورة متساويتين.',
  },
  '≠': {
    tr: 'İki değerin eşit olmadığını gösterir.',
    nl: 'Twee waarden zijn niet gelijk.',
    vi: 'Hai giá trị không bằng nhau.',
    ar: 'القيمتان غير متساويتين.',
  },
  '±': {
    tr: 'Artı veya eksi: iki olası değer veya ölçüm toleransı.',
    nl: 'Plus of min: twee mogelijke waarden of een meettolerantie.',
    vi: 'Cộng hoặc trừ: hai giá trị có thể hoặc sai số đo.',
    ar: 'زائد أو ناقص: قيمتان محتملتان أو سماحية قياس.',
  },
  '−': {
    tr: 'Çıkarma ve negatif sayılar için matematiksel eksi; kısa veya uzun çizgiden farklıdır.',
    nl: 'Wiskundig minteken voor aftrekken en negatieve getallen; geen koppelteken of gedachtestreepje.',
    vi: 'Dấu trừ toán học cho phép trừ và số âm, khác gạch nối hoặc gạch ngang.',
    ar: 'ناقص رياضي للطرح والأعداد السالبة، يختلف عن الشرطة.',
  },
  '×': {
    tr: 'Çarpma işareti; 10 × 20 gibi boyutlar arasında da kullanılır.',
    nl: 'Vermenigvuldigingsteken, ook tussen afmetingen zoals 10 × 20.',
    vi: 'Dấu nhân, cũng dùng giữa kích thước như 10 × 20.',
    ar: 'علامة ضرب، وتُستخدم بين الأبعاد مثل 10 × 20.',
  },
  '·': {
    tr: 'Çarpma veya metinde ayırıcı olarak kullanılan orta nokta.',
    nl: 'Gecentreerde punt voor vermenigvuldiging of als scheidingsteken.',
    vi: 'Dấu chấm giữa cho phép nhân hoặc phân cách văn bản.',
    ar: 'نقطة وسطية للضرب أو للفصل في النص.',
  },
  '∞': {
    tr: 'Sınırsız miktarı veya sonu olmayan süreci gösterir.',
    nl: 'Onbegrensde hoeveelheid of een proces zonder einde.',
    vi: 'Lượng không giới hạn hoặc quá trình không kết thúc.',
    ar: 'كمية غير محدودة أو عملية بلا نهاية.',
  },
} as Record<string, Record<string, string>>;
export const symbolDefinitions = Object.fromEntries(
  mathDefinitions.map(([symbol, ...values]) => [
    symbol,
    {
      ...Object.fromEntries(
        definitionLocales.map((locale, index) => [locale, values[index]]),
      ),
      ...additionalDefinitions[symbol],
    },
  ]),
) as Record<string, Record<Locale, string>>;

export const accentSearchMetadata = {
  tr: [
    'aksan|vurgu|harf üstü',
    'Harfi değiştirir. İşareti seçtikten sonra birleşim için harf, bağımsız işaret için boşluk girin.',
  ],
  nl: [
    'accent|diakritisch|boven letter',
    'Verandert een letter. Typ na het kiezen een letter om te combineren of een spatie voor het losse teken.',
  ],
  vi: [
    'dấu|dấu phụ|dấu nhấn',
    'Biến đổi chữ. Sau khi chọn, nhập chữ để kết hợp hoặc dấu cách để có dấu đứng riêng.',
  ],
  ar: [
    'علامة|نبر|فوق الحرف',
    'يعدّل الحرف. بعد اختياره اكتب حرفًا للدمج أو مسافة للحصول على العلامة مستقلة.',
  ],

  en: [
    'accent|diacritic|stress|above letter',
    'A diacritic. Modifies a letter. After choosing it, type a letter to combine them, or Space for the standalone sign.',
  ],
  ru: [
    'диакритика|акцент|надстрочный знак|над буквой',
    'Диакритический знак. Изменяет букву. После его выбора наберите букву для сочетания или пробел для отдельного знака.',
  ],
  pl: [
    'diakrytyka|akcent|nad literą',
    'Znak diakrytyczny. Modyfikuje literę. Po jego wybraniu wpisz literę albo spację, aby uzyskać osobny znak.',
  ],
  fr: [
    'diacritique|accent|sur une lettre',
    'Un signe diacritique. Modifie une lettre. Après sa sélection, tapez une lettre pour les combiner, ou une espace pour le signe isolé.',
  ],
  de: [
    'Diakritikum|Akzent|über Buchstabe',
    'Ein diakritisches Zeichen. Verändert einen Buchstaben. Danach einen Buchstaben zum Kombinieren oder ein Leerzeichen für das einzelne Zeichen eingeben.',
  ],
  es: [
    'diacrítico|acento|sobre letra',
    'Un signo diacrítico. Modifica una letra. Tras elegirlo, escribe una letra para combinarlos o un espacio para el signo separado.',
  ],
  pt: [
    'diacrítico|acento|sobre letra',
    'Um sinal diacrítico. Modifica uma letra. Após o selecionar, escreva uma letra para os combinar ou um espaço para o sinal isolado.',
  ],
  it: [
    'diacritico|accento|sopra lettera',
    'Un segno diacritico. Modifica una lettera. Dopo averlo scelto, digita una lettera per combinarli o uno spazio per il segno isolato.',
  ],
  ro: [
    'diacritic|accent|deasupra literei',
    'Un semn diacritic. Modifică o literă. După selectare, tastează o literă pentru combinare sau un spațiu pentru semnul separat.',
  ],
  he: [
    'סימן דיאקריטי|הטעמה|מעל אות',
    'סימן דיאקריטי. משנה אות. לאחר בחירתו מקלידים אות לשילוב, או רווח לקבלת הסימן בנפרד.',
  ],
} satisfies Record<Locale, [string, string]>;
