// Generated by tools/symbol-data-files.mjs.
const loaders = [
  () => import('./names-001.ts'),
  () => import('./names-002.ts'),
  () => import('./names-003.ts'),
  () => import('./names-004.ts'),
  () => import('./names-005.ts'),
];

export async function loadData(): Promise<Record<string, unknown>> {
  const parts = await Promise.all(loaders.map((load) => load()));
  const result: Record<string, unknown> = {};
  for (const part of parts) {
    Object.assign(result, part.default);
  }
  return result;
}
